/*
MetalSoft REST API

Testing LogicalNetworkInterconnectAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package sdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/metalsoft-io/metalcloud-sdk-go"
)

func Test_sdk_LogicalNetworkInterconnectAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test LogicalNetworkInterconnectAPIService AddLogicalNetworkToLogicalNetworkInterconnect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.AddLogicalNetworkToLogicalNetworkInterconnect(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService CreateLogicalNetworkInterconnect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.CreateLogicalNetworkInterconnect(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService DeleteLogicalNetworkInterconnect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		httpRes, err := apiClient.LogicalNetworkInterconnectAPI.DeleteLogicalNetworkInterconnect(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService GetLogicalNetworkInterconnectById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.GetLogicalNetworkInterconnectById(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService GetLogicalNetworkInterconnectLogicalNetworkById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32
		var logicalNetworkId int32

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.GetLogicalNetworkInterconnectLogicalNetworkById(context.Background(), id, logicalNetworkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService GetLogicalNetworkInterconnectLogicalNetworks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.GetLogicalNetworkInterconnectLogicalNetworks(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService GetLogicalNetworkInterconnects", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.GetLogicalNetworkInterconnects(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService RemoveLogicalNetworkFromLogicalNetworkInterconnect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32
		var logicalNetworkId int32

		httpRes, err := apiClient.LogicalNetworkInterconnectAPI.RemoveLogicalNetworkFromLogicalNetworkInterconnect(context.Background(), id, logicalNetworkId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test LogicalNetworkInterconnectAPIService UpdateLogicalNetworkInterconnect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.LogicalNetworkInterconnectAPI.UpdateLogicalNetworkInterconnect(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
