/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the AuthenticationRequestPropertiesMySqlDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthenticationRequestPropertiesMySqlDto{}

// AuthenticationRequestPropertiesMySqlDto struct for AuthenticationRequestPropertiesMySqlDto
type AuthenticationRequestPropertiesMySqlDto struct {
	// The one-time password.
	OneTimePassword *string `json:"oneTimePassword,omitempty"`
	// Whether to remember the login
	RememberLogin *bool `json:"rememberLogin,omitempty"`
	// Whether to test the credentials
	TestCredentials *bool `json:"testCredentials,omitempty"`
	// The email of the user
	Email string `json:"email"`
	// The password of the user
	Password string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _AuthenticationRequestPropertiesMySqlDto AuthenticationRequestPropertiesMySqlDto

// NewAuthenticationRequestPropertiesMySqlDto instantiates a new AuthenticationRequestPropertiesMySqlDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthenticationRequestPropertiesMySqlDto(email string, password string) *AuthenticationRequestPropertiesMySqlDto {
	this := AuthenticationRequestPropertiesMySqlDto{}
	var rememberLogin bool = true
	this.RememberLogin = &rememberLogin
	var testCredentials bool = false
	this.TestCredentials = &testCredentials
	this.Email = email
	this.Password = password
	return &this
}

// NewAuthenticationRequestPropertiesMySqlDtoWithDefaults instantiates a new AuthenticationRequestPropertiesMySqlDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthenticationRequestPropertiesMySqlDtoWithDefaults() *AuthenticationRequestPropertiesMySqlDto {
	this := AuthenticationRequestPropertiesMySqlDto{}
	var rememberLogin bool = true
	this.RememberLogin = &rememberLogin
	var testCredentials bool = false
	this.TestCredentials = &testCredentials
	return &this
}

// GetOneTimePassword returns the OneTimePassword field value if set, zero value otherwise.
func (o *AuthenticationRequestPropertiesMySqlDto) GetOneTimePassword() string {
	if o == nil || IsNil(o.OneTimePassword) {
		var ret string
		return ret
	}
	return *o.OneTimePassword
}

// GetOneTimePasswordOk returns a tuple with the OneTimePassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) GetOneTimePasswordOk() (*string, bool) {
	if o == nil || IsNil(o.OneTimePassword) {
		return nil, false
	}
	return o.OneTimePassword, true
}

// HasOneTimePassword returns a boolean if a field has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) HasOneTimePassword() bool {
	if o != nil && !IsNil(o.OneTimePassword) {
		return true
	}

	return false
}

// SetOneTimePassword gets a reference to the given string and assigns it to the OneTimePassword field.
func (o *AuthenticationRequestPropertiesMySqlDto) SetOneTimePassword(v string) {
	o.OneTimePassword = &v
}

// GetRememberLogin returns the RememberLogin field value if set, zero value otherwise.
func (o *AuthenticationRequestPropertiesMySqlDto) GetRememberLogin() bool {
	if o == nil || IsNil(o.RememberLogin) {
		var ret bool
		return ret
	}
	return *o.RememberLogin
}

// GetRememberLoginOk returns a tuple with the RememberLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) GetRememberLoginOk() (*bool, bool) {
	if o == nil || IsNil(o.RememberLogin) {
		return nil, false
	}
	return o.RememberLogin, true
}

// HasRememberLogin returns a boolean if a field has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) HasRememberLogin() bool {
	if o != nil && !IsNil(o.RememberLogin) {
		return true
	}

	return false
}

// SetRememberLogin gets a reference to the given bool and assigns it to the RememberLogin field.
func (o *AuthenticationRequestPropertiesMySqlDto) SetRememberLogin(v bool) {
	o.RememberLogin = &v
}

// GetTestCredentials returns the TestCredentials field value if set, zero value otherwise.
func (o *AuthenticationRequestPropertiesMySqlDto) GetTestCredentials() bool {
	if o == nil || IsNil(o.TestCredentials) {
		var ret bool
		return ret
	}
	return *o.TestCredentials
}

// GetTestCredentialsOk returns a tuple with the TestCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) GetTestCredentialsOk() (*bool, bool) {
	if o == nil || IsNil(o.TestCredentials) {
		return nil, false
	}
	return o.TestCredentials, true
}

// HasTestCredentials returns a boolean if a field has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) HasTestCredentials() bool {
	if o != nil && !IsNil(o.TestCredentials) {
		return true
	}

	return false
}

// SetTestCredentials gets a reference to the given bool and assigns it to the TestCredentials field.
func (o *AuthenticationRequestPropertiesMySqlDto) SetTestCredentials(v bool) {
	o.TestCredentials = &v
}

// GetEmail returns the Email field value
func (o *AuthenticationRequestPropertiesMySqlDto) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *AuthenticationRequestPropertiesMySqlDto) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value
func (o *AuthenticationRequestPropertiesMySqlDto) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *AuthenticationRequestPropertiesMySqlDto) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *AuthenticationRequestPropertiesMySqlDto) SetPassword(v string) {
	o.Password = v
}

func (o AuthenticationRequestPropertiesMySqlDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthenticationRequestPropertiesMySqlDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OneTimePassword) {
		toSerialize["oneTimePassword"] = o.OneTimePassword
	}
	if !IsNil(o.RememberLogin) {
		toSerialize["rememberLogin"] = o.RememberLogin
	}
	if !IsNil(o.TestCredentials) {
		toSerialize["testCredentials"] = o.TestCredentials
	}
	toSerialize["email"] = o.Email
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthenticationRequestPropertiesMySqlDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthenticationRequestPropertiesMySqlDto := _AuthenticationRequestPropertiesMySqlDto{}

	err = json.Unmarshal(data, &varAuthenticationRequestPropertiesMySqlDto)

	if err != nil {
		return err
	}

	*o = AuthenticationRequestPropertiesMySqlDto(varAuthenticationRequestPropertiesMySqlDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "oneTimePassword")
		delete(additionalProperties, "rememberLogin")
		delete(additionalProperties, "testCredentials")
		delete(additionalProperties, "email")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthenticationRequestPropertiesMySqlDto struct {
	value *AuthenticationRequestPropertiesMySqlDto
	isSet bool
}

func (v NullableAuthenticationRequestPropertiesMySqlDto) Get() *AuthenticationRequestPropertiesMySqlDto {
	return v.value
}

func (v *NullableAuthenticationRequestPropertiesMySqlDto) Set(val *AuthenticationRequestPropertiesMySqlDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthenticationRequestPropertiesMySqlDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthenticationRequestPropertiesMySqlDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthenticationRequestPropertiesMySqlDto(val *AuthenticationRequestPropertiesMySqlDto) *NullableAuthenticationRequestPropertiesMySqlDto {
	return &NullableAuthenticationRequestPropertiesMySqlDto{value: val, isSet: true}
}

func (v NullableAuthenticationRequestPropertiesMySqlDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthenticationRequestPropertiesMySqlDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


