/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the LogicalNetworkConfigVxlanProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogicalNetworkConfigVxlanProperties{}

// LogicalNetworkConfigVxlanProperties struct for LogicalNetworkConfigVxlanProperties
type LogicalNetworkConfigVxlanProperties struct {
	VniAllocationStrategies []VniAllocationStrategy1 `json:"vniAllocationStrategies"`
	AdditionalProperties map[string]interface{}
}

type _LogicalNetworkConfigVxlanProperties LogicalNetworkConfigVxlanProperties

// NewLogicalNetworkConfigVxlanProperties instantiates a new LogicalNetworkConfigVxlanProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogicalNetworkConfigVxlanProperties(vniAllocationStrategies []VniAllocationStrategy1) *LogicalNetworkConfigVxlanProperties {
	this := LogicalNetworkConfigVxlanProperties{}
	this.VniAllocationStrategies = vniAllocationStrategies
	return &this
}

// NewLogicalNetworkConfigVxlanPropertiesWithDefaults instantiates a new LogicalNetworkConfigVxlanProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogicalNetworkConfigVxlanPropertiesWithDefaults() *LogicalNetworkConfigVxlanProperties {
	this := LogicalNetworkConfigVxlanProperties{}
	return &this
}

// GetVniAllocationStrategies returns the VniAllocationStrategies field value
func (o *LogicalNetworkConfigVxlanProperties) GetVniAllocationStrategies() []VniAllocationStrategy1 {
	if o == nil {
		var ret []VniAllocationStrategy1
		return ret
	}

	return o.VniAllocationStrategies
}

// GetVniAllocationStrategiesOk returns a tuple with the VniAllocationStrategies field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkConfigVxlanProperties) GetVniAllocationStrategiesOk() ([]VniAllocationStrategy1, bool) {
	if o == nil {
		return nil, false
	}
	return o.VniAllocationStrategies, true
}

// SetVniAllocationStrategies sets field value
func (o *LogicalNetworkConfigVxlanProperties) SetVniAllocationStrategies(v []VniAllocationStrategy1) {
	o.VniAllocationStrategies = v
}

func (o LogicalNetworkConfigVxlanProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogicalNetworkConfigVxlanProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["vniAllocationStrategies"] = o.VniAllocationStrategies

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LogicalNetworkConfigVxlanProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"vniAllocationStrategies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogicalNetworkConfigVxlanProperties := _LogicalNetworkConfigVxlanProperties{}

	err = json.Unmarshal(data, &varLogicalNetworkConfigVxlanProperties)

	if err != nil {
		return err
	}

	*o = LogicalNetworkConfigVxlanProperties(varLogicalNetworkConfigVxlanProperties)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "vniAllocationStrategies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLogicalNetworkConfigVxlanProperties struct {
	value *LogicalNetworkConfigVxlanProperties
	isSet bool
}

func (v NullableLogicalNetworkConfigVxlanProperties) Get() *LogicalNetworkConfigVxlanProperties {
	return v.value
}

func (v *NullableLogicalNetworkConfigVxlanProperties) Set(val *LogicalNetworkConfigVxlanProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableLogicalNetworkConfigVxlanProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableLogicalNetworkConfigVxlanProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogicalNetworkConfigVxlanProperties(val *LogicalNetworkConfigVxlanProperties) *NullableLogicalNetworkConfigVxlanProperties {
	return &NullableLogicalNetworkConfigVxlanProperties{value: val, isSet: true}
}

func (v NullableLogicalNetworkConfigVxlanProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogicalNetworkConfigVxlanProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


