/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the InfinibandFabric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfinibandFabric{}

// InfinibandFabric struct for InfinibandFabric
type InfinibandFabric struct {
	// The type of network fabric
	FabricType FabricType `json:"fabricType"`
	// Enables gNMI monitoring for telemetry data collection using the gNMI protocol.
	GnmiMonitoringEnabled *bool `json:"gnmiMonitoringEnabled,omitempty"`
	// Enables server-only operation mode on the network fabric.
	ServerOnlyOperationEnabled *bool `json:"serverOnlyOperationEnabled,omitempty"`
	// Enables syslog monitoring for capturing system logs for diagnostics and troubleshooting.
	SyslogMonitoringEnabled *bool `json:"syslogMonitoringEnabled,omitempty"`
	// Link Aggregation (LAG) ranges in the format \"start-end\"; each range must be within the bounds of 1 to 4096.
	LagRanges []string `json:"lagRanges,omitempty"`
	// PKey ranges that should be prevented from automatic cleanup. Format must be \"start-end\".
	PreventPKeyCleanup []string `json:"preventPKeyCleanup,omitempty"`
	// Reserved PKey ranges that are excluded from general allocation. Must follow the \"start-end\" format.
	ReservedPkeys []string `json:"reservedPkeys,omitempty"`
	// Array of PKey range strings in \"start-end\" format to be used in configuration.
	PkeyRanges []string `json:"pkeyRanges,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InfinibandFabric InfinibandFabric

// NewInfinibandFabric instantiates a new InfinibandFabric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfinibandFabric(fabricType FabricType) *InfinibandFabric {
	this := InfinibandFabric{}
	this.FabricType = fabricType
	return &this
}

// NewInfinibandFabricWithDefaults instantiates a new InfinibandFabric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfinibandFabricWithDefaults() *InfinibandFabric {
	this := InfinibandFabric{}
	return &this
}

// GetFabricType returns the FabricType field value
func (o *InfinibandFabric) GetFabricType() FabricType {
	if o == nil {
		var ret FabricType
		return ret
	}

	return o.FabricType
}

// GetFabricTypeOk returns a tuple with the FabricType field value
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetFabricTypeOk() (*FabricType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FabricType, true
}

// SetFabricType sets field value
func (o *InfinibandFabric) SetFabricType(v FabricType) {
	o.FabricType = v
}

// GetGnmiMonitoringEnabled returns the GnmiMonitoringEnabled field value if set, zero value otherwise.
func (o *InfinibandFabric) GetGnmiMonitoringEnabled() bool {
	if o == nil || IsNil(o.GnmiMonitoringEnabled) {
		var ret bool
		return ret
	}
	return *o.GnmiMonitoringEnabled
}

// GetGnmiMonitoringEnabledOk returns a tuple with the GnmiMonitoringEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetGnmiMonitoringEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.GnmiMonitoringEnabled) {
		return nil, false
	}
	return o.GnmiMonitoringEnabled, true
}

// HasGnmiMonitoringEnabled returns a boolean if a field has been set.
func (o *InfinibandFabric) HasGnmiMonitoringEnabled() bool {
	if o != nil && !IsNil(o.GnmiMonitoringEnabled) {
		return true
	}

	return false
}

// SetGnmiMonitoringEnabled gets a reference to the given bool and assigns it to the GnmiMonitoringEnabled field.
func (o *InfinibandFabric) SetGnmiMonitoringEnabled(v bool) {
	o.GnmiMonitoringEnabled = &v
}

// GetServerOnlyOperationEnabled returns the ServerOnlyOperationEnabled field value if set, zero value otherwise.
func (o *InfinibandFabric) GetServerOnlyOperationEnabled() bool {
	if o == nil || IsNil(o.ServerOnlyOperationEnabled) {
		var ret bool
		return ret
	}
	return *o.ServerOnlyOperationEnabled
}

// GetServerOnlyOperationEnabledOk returns a tuple with the ServerOnlyOperationEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetServerOnlyOperationEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ServerOnlyOperationEnabled) {
		return nil, false
	}
	return o.ServerOnlyOperationEnabled, true
}

// HasServerOnlyOperationEnabled returns a boolean if a field has been set.
func (o *InfinibandFabric) HasServerOnlyOperationEnabled() bool {
	if o != nil && !IsNil(o.ServerOnlyOperationEnabled) {
		return true
	}

	return false
}

// SetServerOnlyOperationEnabled gets a reference to the given bool and assigns it to the ServerOnlyOperationEnabled field.
func (o *InfinibandFabric) SetServerOnlyOperationEnabled(v bool) {
	o.ServerOnlyOperationEnabled = &v
}

// GetSyslogMonitoringEnabled returns the SyslogMonitoringEnabled field value if set, zero value otherwise.
func (o *InfinibandFabric) GetSyslogMonitoringEnabled() bool {
	if o == nil || IsNil(o.SyslogMonitoringEnabled) {
		var ret bool
		return ret
	}
	return *o.SyslogMonitoringEnabled
}

// GetSyslogMonitoringEnabledOk returns a tuple with the SyslogMonitoringEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetSyslogMonitoringEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SyslogMonitoringEnabled) {
		return nil, false
	}
	return o.SyslogMonitoringEnabled, true
}

// HasSyslogMonitoringEnabled returns a boolean if a field has been set.
func (o *InfinibandFabric) HasSyslogMonitoringEnabled() bool {
	if o != nil && !IsNil(o.SyslogMonitoringEnabled) {
		return true
	}

	return false
}

// SetSyslogMonitoringEnabled gets a reference to the given bool and assigns it to the SyslogMonitoringEnabled field.
func (o *InfinibandFabric) SetSyslogMonitoringEnabled(v bool) {
	o.SyslogMonitoringEnabled = &v
}

// GetLagRanges returns the LagRanges field value if set, zero value otherwise.
func (o *InfinibandFabric) GetLagRanges() []string {
	if o == nil || IsNil(o.LagRanges) {
		var ret []string
		return ret
	}
	return o.LagRanges
}

// GetLagRangesOk returns a tuple with the LagRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetLagRangesOk() ([]string, bool) {
	if o == nil || IsNil(o.LagRanges) {
		return nil, false
	}
	return o.LagRanges, true
}

// HasLagRanges returns a boolean if a field has been set.
func (o *InfinibandFabric) HasLagRanges() bool {
	if o != nil && !IsNil(o.LagRanges) {
		return true
	}

	return false
}

// SetLagRanges gets a reference to the given []string and assigns it to the LagRanges field.
func (o *InfinibandFabric) SetLagRanges(v []string) {
	o.LagRanges = v
}

// GetPreventPKeyCleanup returns the PreventPKeyCleanup field value if set, zero value otherwise.
func (o *InfinibandFabric) GetPreventPKeyCleanup() []string {
	if o == nil || IsNil(o.PreventPKeyCleanup) {
		var ret []string
		return ret
	}
	return o.PreventPKeyCleanup
}

// GetPreventPKeyCleanupOk returns a tuple with the PreventPKeyCleanup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetPreventPKeyCleanupOk() ([]string, bool) {
	if o == nil || IsNil(o.PreventPKeyCleanup) {
		return nil, false
	}
	return o.PreventPKeyCleanup, true
}

// HasPreventPKeyCleanup returns a boolean if a field has been set.
func (o *InfinibandFabric) HasPreventPKeyCleanup() bool {
	if o != nil && !IsNil(o.PreventPKeyCleanup) {
		return true
	}

	return false
}

// SetPreventPKeyCleanup gets a reference to the given []string and assigns it to the PreventPKeyCleanup field.
func (o *InfinibandFabric) SetPreventPKeyCleanup(v []string) {
	o.PreventPKeyCleanup = v
}

// GetReservedPkeys returns the ReservedPkeys field value if set, zero value otherwise.
func (o *InfinibandFabric) GetReservedPkeys() []string {
	if o == nil || IsNil(o.ReservedPkeys) {
		var ret []string
		return ret
	}
	return o.ReservedPkeys
}

// GetReservedPkeysOk returns a tuple with the ReservedPkeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetReservedPkeysOk() ([]string, bool) {
	if o == nil || IsNil(o.ReservedPkeys) {
		return nil, false
	}
	return o.ReservedPkeys, true
}

// HasReservedPkeys returns a boolean if a field has been set.
func (o *InfinibandFabric) HasReservedPkeys() bool {
	if o != nil && !IsNil(o.ReservedPkeys) {
		return true
	}

	return false
}

// SetReservedPkeys gets a reference to the given []string and assigns it to the ReservedPkeys field.
func (o *InfinibandFabric) SetReservedPkeys(v []string) {
	o.ReservedPkeys = v
}

// GetPkeyRanges returns the PkeyRanges field value if set, zero value otherwise.
func (o *InfinibandFabric) GetPkeyRanges() []string {
	if o == nil || IsNil(o.PkeyRanges) {
		var ret []string
		return ret
	}
	return o.PkeyRanges
}

// GetPkeyRangesOk returns a tuple with the PkeyRanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfinibandFabric) GetPkeyRangesOk() ([]string, bool) {
	if o == nil || IsNil(o.PkeyRanges) {
		return nil, false
	}
	return o.PkeyRanges, true
}

// HasPkeyRanges returns a boolean if a field has been set.
func (o *InfinibandFabric) HasPkeyRanges() bool {
	if o != nil && !IsNil(o.PkeyRanges) {
		return true
	}

	return false
}

// SetPkeyRanges gets a reference to the given []string and assigns it to the PkeyRanges field.
func (o *InfinibandFabric) SetPkeyRanges(v []string) {
	o.PkeyRanges = v
}

func (o InfinibandFabric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfinibandFabric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["fabricType"] = o.FabricType
	if !IsNil(o.GnmiMonitoringEnabled) {
		toSerialize["gnmiMonitoringEnabled"] = o.GnmiMonitoringEnabled
	}
	if !IsNil(o.ServerOnlyOperationEnabled) {
		toSerialize["serverOnlyOperationEnabled"] = o.ServerOnlyOperationEnabled
	}
	if !IsNil(o.SyslogMonitoringEnabled) {
		toSerialize["syslogMonitoringEnabled"] = o.SyslogMonitoringEnabled
	}
	if !IsNil(o.LagRanges) {
		toSerialize["lagRanges"] = o.LagRanges
	}
	if !IsNil(o.PreventPKeyCleanup) {
		toSerialize["preventPKeyCleanup"] = o.PreventPKeyCleanup
	}
	if !IsNil(o.ReservedPkeys) {
		toSerialize["reservedPkeys"] = o.ReservedPkeys
	}
	if !IsNil(o.PkeyRanges) {
		toSerialize["pkeyRanges"] = o.PkeyRanges
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InfinibandFabric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"fabricType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInfinibandFabric := _InfinibandFabric{}

	err = json.Unmarshal(data, &varInfinibandFabric)

	if err != nil {
		return err
	}

	*o = InfinibandFabric(varInfinibandFabric)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "fabricType")
		delete(additionalProperties, "gnmiMonitoringEnabled")
		delete(additionalProperties, "serverOnlyOperationEnabled")
		delete(additionalProperties, "syslogMonitoringEnabled")
		delete(additionalProperties, "lagRanges")
		delete(additionalProperties, "preventPKeyCleanup")
		delete(additionalProperties, "reservedPkeys")
		delete(additionalProperties, "pkeyRanges")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInfinibandFabric struct {
	value *InfinibandFabric
	isSet bool
}

func (v NullableInfinibandFabric) Get() *InfinibandFabric {
	return v.value
}

func (v *NullableInfinibandFabric) Set(val *InfinibandFabric) {
	v.value = val
	v.isSet = true
}

func (v NullableInfinibandFabric) IsSet() bool {
	return v.isSet
}

func (v *NullableInfinibandFabric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfinibandFabric(val *InfinibandFabric) *NullableInfinibandFabric {
	return &NullableInfinibandFabric{value: val, isSet: true}
}

func (v NullableInfinibandFabric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfinibandFabric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


