/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the VMPoolHostInterfaces type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VMPoolHostInterfaces{}

// VMPoolHostInterfaces struct for VMPoolHostInterfaces
type VMPoolHostInterfaces struct {
	// VM Pool Host Interface ID
	Id int64 `json:"id"`
	// VM Pool Host ID
	HostId int64 `json:"hostId"`
	// Status of the VM Pool Host Interface
	Status VMPoolHostInterfaceStatus `json:"status"`
	// Name of the VM Pool Host Interface
	Name string `json:"name"`
	// MAC Address of the VM Pool Host Interface
	MacAddress string `json:"macAddress"`
	// Fabric type of the VM Pool Host Interface
	Fabric *GenericNetworkFabric `json:"fabric,omitempty"`
	// Network device assignments for this interface
	NetworkDevices []VMPoolHostInterfaceNetworkDevice `json:"networkDevices,omitempty"`
	// Reference links
	Links []Link `json:"links,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _VMPoolHostInterfaces VMPoolHostInterfaces

// NewVMPoolHostInterfaces instantiates a new VMPoolHostInterfaces object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVMPoolHostInterfaces(id int64, hostId int64, status VMPoolHostInterfaceStatus, name string, macAddress string) *VMPoolHostInterfaces {
	this := VMPoolHostInterfaces{}
	this.Id = id
	this.HostId = hostId
	this.Status = status
	this.Name = name
	this.MacAddress = macAddress
	return &this
}

// NewVMPoolHostInterfacesWithDefaults instantiates a new VMPoolHostInterfaces object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVMPoolHostInterfacesWithDefaults() *VMPoolHostInterfaces {
	this := VMPoolHostInterfaces{}
	return &this
}

// GetId returns the Id field value
func (o *VMPoolHostInterfaces) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VMPoolHostInterfaces) SetId(v int64) {
	o.Id = v
}

// GetHostId returns the HostId field value
func (o *VMPoolHostInterfaces) GetHostId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.HostId
}

// GetHostIdOk returns a tuple with the HostId field value
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetHostIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostId, true
}

// SetHostId sets field value
func (o *VMPoolHostInterfaces) SetHostId(v int64) {
	o.HostId = v
}

// GetStatus returns the Status field value
func (o *VMPoolHostInterfaces) GetStatus() VMPoolHostInterfaceStatus {
	if o == nil {
		var ret VMPoolHostInterfaceStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetStatusOk() (*VMPoolHostInterfaceStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *VMPoolHostInterfaces) SetStatus(v VMPoolHostInterfaceStatus) {
	o.Status = v
}

// GetName returns the Name field value
func (o *VMPoolHostInterfaces) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VMPoolHostInterfaces) SetName(v string) {
	o.Name = v
}

// GetMacAddress returns the MacAddress field value
func (o *VMPoolHostInterfaces) GetMacAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MacAddress
}

// GetMacAddressOk returns a tuple with the MacAddress field value
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetMacAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MacAddress, true
}

// SetMacAddress sets field value
func (o *VMPoolHostInterfaces) SetMacAddress(v string) {
	o.MacAddress = v
}

// GetFabric returns the Fabric field value if set, zero value otherwise.
func (o *VMPoolHostInterfaces) GetFabric() GenericNetworkFabric {
	if o == nil || IsNil(o.Fabric) {
		var ret GenericNetworkFabric
		return ret
	}
	return *o.Fabric
}

// GetFabricOk returns a tuple with the Fabric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetFabricOk() (*GenericNetworkFabric, bool) {
	if o == nil || IsNil(o.Fabric) {
		return nil, false
	}
	return o.Fabric, true
}

// HasFabric returns a boolean if a field has been set.
func (o *VMPoolHostInterfaces) HasFabric() bool {
	if o != nil && !IsNil(o.Fabric) {
		return true
	}

	return false
}

// SetFabric gets a reference to the given GenericNetworkFabric and assigns it to the Fabric field.
func (o *VMPoolHostInterfaces) SetFabric(v GenericNetworkFabric) {
	o.Fabric = &v
}

// GetNetworkDevices returns the NetworkDevices field value if set, zero value otherwise.
func (o *VMPoolHostInterfaces) GetNetworkDevices() []VMPoolHostInterfaceNetworkDevice {
	if o == nil || IsNil(o.NetworkDevices) {
		var ret []VMPoolHostInterfaceNetworkDevice
		return ret
	}
	return o.NetworkDevices
}

// GetNetworkDevicesOk returns a tuple with the NetworkDevices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetNetworkDevicesOk() ([]VMPoolHostInterfaceNetworkDevice, bool) {
	if o == nil || IsNil(o.NetworkDevices) {
		return nil, false
	}
	return o.NetworkDevices, true
}

// HasNetworkDevices returns a boolean if a field has been set.
func (o *VMPoolHostInterfaces) HasNetworkDevices() bool {
	if o != nil && !IsNil(o.NetworkDevices) {
		return true
	}

	return false
}

// SetNetworkDevices gets a reference to the given []VMPoolHostInterfaceNetworkDevice and assigns it to the NetworkDevices field.
func (o *VMPoolHostInterfaces) SetNetworkDevices(v []VMPoolHostInterfaceNetworkDevice) {
	o.NetworkDevices = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *VMPoolHostInterfaces) GetLinks() []Link {
	if o == nil || IsNil(o.Links) {
		var ret []Link
		return ret
	}
	return o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VMPoolHostInterfaces) GetLinksOk() ([]Link, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *VMPoolHostInterfaces) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given []Link and assigns it to the Links field.
func (o *VMPoolHostInterfaces) SetLinks(v []Link) {
	o.Links = v
}

func (o VMPoolHostInterfaces) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VMPoolHostInterfaces) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["hostId"] = o.HostId
	toSerialize["status"] = o.Status
	toSerialize["name"] = o.Name
	toSerialize["macAddress"] = o.MacAddress
	if !IsNil(o.Fabric) {
		toSerialize["fabric"] = o.Fabric
	}
	if !IsNil(o.NetworkDevices) {
		toSerialize["networkDevices"] = o.NetworkDevices
	}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VMPoolHostInterfaces) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"hostId",
		"status",
		"name",
		"macAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVMPoolHostInterfaces := _VMPoolHostInterfaces{}

	err = json.Unmarshal(data, &varVMPoolHostInterfaces)

	if err != nil {
		return err
	}

	*o = VMPoolHostInterfaces(varVMPoolHostInterfaces)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "hostId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "name")
		delete(additionalProperties, "macAddress")
		delete(additionalProperties, "fabric")
		delete(additionalProperties, "networkDevices")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVMPoolHostInterfaces struct {
	value *VMPoolHostInterfaces
	isSet bool
}

func (v NullableVMPoolHostInterfaces) Get() *VMPoolHostInterfaces {
	return v.value
}

func (v *NullableVMPoolHostInterfaces) Set(val *VMPoolHostInterfaces) {
	v.value = val
	v.isSet = true
}

func (v NullableVMPoolHostInterfaces) IsSet() bool {
	return v.isSet
}

func (v *NullableVMPoolHostInterfaces) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVMPoolHostInterfaces(val *VMPoolHostInterfaces) *NullableVMPoolHostInterfaces {
	return &NullableVMPoolHostInterfaces{value: val, isSet: true}
}

func (v NullableVMPoolHostInterfaces) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVMPoolHostInterfaces) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


