/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the StorageCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StorageCredentials{}

// StorageCredentials struct for StorageCredentials
type StorageCredentials struct {
	// The username to use.
	Username string `json:"username"`
	// The password to use.
	Password string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _StorageCredentials StorageCredentials

// NewStorageCredentials instantiates a new StorageCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageCredentials(username string, password string) *StorageCredentials {
	this := StorageCredentials{}
	this.Username = username
	this.Password = password
	return &this
}

// NewStorageCredentialsWithDefaults instantiates a new StorageCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageCredentialsWithDefaults() *StorageCredentials {
	this := StorageCredentials{}
	return &this
}

// GetUsername returns the Username field value
func (o *StorageCredentials) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *StorageCredentials) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *StorageCredentials) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *StorageCredentials) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *StorageCredentials) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *StorageCredentials) SetPassword(v string) {
	o.Password = v
}

func (o StorageCredentials) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StorageCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StorageCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStorageCredentials := _StorageCredentials{}

	err = json.Unmarshal(data, &varStorageCredentials)

	if err != nil {
		return err
	}

	*o = StorageCredentials(varStorageCredentials)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStorageCredentials struct {
	value *StorageCredentials
	isSet bool
}

func (v NullableStorageCredentials) Get() *StorageCredentials {
	return v.value
}

func (v *NullableStorageCredentials) Set(val *StorageCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageCredentials(val *StorageCredentials) *NullableStorageCredentials {
	return &NullableStorageCredentials{value: val, isSet: true}
}

func (v NullableStorageCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


