/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the InfiniBandFabricDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InfiniBandFabricDto{}

// InfiniBandFabricDto struct for InfiniBandFabricDto
type InfiniBandFabricDto struct {
	DefaultNetworkProfileId float32 `json:"defaultNetworkProfileId"`
	GnmiMonitoringEnabled *bool `json:"gnmiMonitoringEnabled,omitempty"`
	SyslogMonitoringEnabled *bool `json:"syslogMonitoringEnabled,omitempty"`
	ZeroTouchEnabled *bool `json:"zeroTouchEnabled,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _InfiniBandFabricDto InfiniBandFabricDto

// NewInfiniBandFabricDto instantiates a new InfiniBandFabricDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInfiniBandFabricDto(defaultNetworkProfileId float32) *InfiniBandFabricDto {
	this := InfiniBandFabricDto{}
	this.DefaultNetworkProfileId = defaultNetworkProfileId
	return &this
}

// NewInfiniBandFabricDtoWithDefaults instantiates a new InfiniBandFabricDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInfiniBandFabricDtoWithDefaults() *InfiniBandFabricDto {
	this := InfiniBandFabricDto{}
	return &this
}

// GetDefaultNetworkProfileId returns the DefaultNetworkProfileId field value
func (o *InfiniBandFabricDto) GetDefaultNetworkProfileId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.DefaultNetworkProfileId
}

// GetDefaultNetworkProfileIdOk returns a tuple with the DefaultNetworkProfileId field value
// and a boolean to check if the value has been set.
func (o *InfiniBandFabricDto) GetDefaultNetworkProfileIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultNetworkProfileId, true
}

// SetDefaultNetworkProfileId sets field value
func (o *InfiniBandFabricDto) SetDefaultNetworkProfileId(v float32) {
	o.DefaultNetworkProfileId = v
}

// GetGnmiMonitoringEnabled returns the GnmiMonitoringEnabled field value if set, zero value otherwise.
func (o *InfiniBandFabricDto) GetGnmiMonitoringEnabled() bool {
	if o == nil || IsNil(o.GnmiMonitoringEnabled) {
		var ret bool
		return ret
	}
	return *o.GnmiMonitoringEnabled
}

// GetGnmiMonitoringEnabledOk returns a tuple with the GnmiMonitoringEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandFabricDto) GetGnmiMonitoringEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.GnmiMonitoringEnabled) {
		return nil, false
	}
	return o.GnmiMonitoringEnabled, true
}

// HasGnmiMonitoringEnabled returns a boolean if a field has been set.
func (o *InfiniBandFabricDto) HasGnmiMonitoringEnabled() bool {
	if o != nil && !IsNil(o.GnmiMonitoringEnabled) {
		return true
	}

	return false
}

// SetGnmiMonitoringEnabled gets a reference to the given bool and assigns it to the GnmiMonitoringEnabled field.
func (o *InfiniBandFabricDto) SetGnmiMonitoringEnabled(v bool) {
	o.GnmiMonitoringEnabled = &v
}

// GetSyslogMonitoringEnabled returns the SyslogMonitoringEnabled field value if set, zero value otherwise.
func (o *InfiniBandFabricDto) GetSyslogMonitoringEnabled() bool {
	if o == nil || IsNil(o.SyslogMonitoringEnabled) {
		var ret bool
		return ret
	}
	return *o.SyslogMonitoringEnabled
}

// GetSyslogMonitoringEnabledOk returns a tuple with the SyslogMonitoringEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandFabricDto) GetSyslogMonitoringEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SyslogMonitoringEnabled) {
		return nil, false
	}
	return o.SyslogMonitoringEnabled, true
}

// HasSyslogMonitoringEnabled returns a boolean if a field has been set.
func (o *InfiniBandFabricDto) HasSyslogMonitoringEnabled() bool {
	if o != nil && !IsNil(o.SyslogMonitoringEnabled) {
		return true
	}

	return false
}

// SetSyslogMonitoringEnabled gets a reference to the given bool and assigns it to the SyslogMonitoringEnabled field.
func (o *InfiniBandFabricDto) SetSyslogMonitoringEnabled(v bool) {
	o.SyslogMonitoringEnabled = &v
}

// GetZeroTouchEnabled returns the ZeroTouchEnabled field value if set, zero value otherwise.
func (o *InfiniBandFabricDto) GetZeroTouchEnabled() bool {
	if o == nil || IsNil(o.ZeroTouchEnabled) {
		var ret bool
		return ret
	}
	return *o.ZeroTouchEnabled
}

// GetZeroTouchEnabledOk returns a tuple with the ZeroTouchEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InfiniBandFabricDto) GetZeroTouchEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ZeroTouchEnabled) {
		return nil, false
	}
	return o.ZeroTouchEnabled, true
}

// HasZeroTouchEnabled returns a boolean if a field has been set.
func (o *InfiniBandFabricDto) HasZeroTouchEnabled() bool {
	if o != nil && !IsNil(o.ZeroTouchEnabled) {
		return true
	}

	return false
}

// SetZeroTouchEnabled gets a reference to the given bool and assigns it to the ZeroTouchEnabled field.
func (o *InfiniBandFabricDto) SetZeroTouchEnabled(v bool) {
	o.ZeroTouchEnabled = &v
}

func (o InfiniBandFabricDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InfiniBandFabricDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["defaultNetworkProfileId"] = o.DefaultNetworkProfileId
	if !IsNil(o.GnmiMonitoringEnabled) {
		toSerialize["gnmiMonitoringEnabled"] = o.GnmiMonitoringEnabled
	}
	if !IsNil(o.SyslogMonitoringEnabled) {
		toSerialize["syslogMonitoringEnabled"] = o.SyslogMonitoringEnabled
	}
	if !IsNil(o.ZeroTouchEnabled) {
		toSerialize["zeroTouchEnabled"] = o.ZeroTouchEnabled
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *InfiniBandFabricDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"defaultNetworkProfileId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInfiniBandFabricDto := _InfiniBandFabricDto{}

	err = json.Unmarshal(data, &varInfiniBandFabricDto)

	if err != nil {
		return err
	}

	*o = InfiniBandFabricDto(varInfiniBandFabricDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "defaultNetworkProfileId")
		delete(additionalProperties, "gnmiMonitoringEnabled")
		delete(additionalProperties, "syslogMonitoringEnabled")
		delete(additionalProperties, "zeroTouchEnabled")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableInfiniBandFabricDto struct {
	value *InfiniBandFabricDto
	isSet bool
}

func (v NullableInfiniBandFabricDto) Get() *InfiniBandFabricDto {
	return v.value
}

func (v *NullableInfiniBandFabricDto) Set(val *InfiniBandFabricDto) {
	v.value = val
	v.isSet = true
}

func (v NullableInfiniBandFabricDto) IsSet() bool {
	return v.isSet
}

func (v *NullableInfiniBandFabricDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInfiniBandFabricDto(val *InfiniBandFabricDto) *NullableInfiniBandFabricDto {
	return &NullableInfiniBandFabricDto{value: val, isSet: true}
}

func (v NullableInfiniBandFabricDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInfiniBandFabricDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


