/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the NetworkFabric type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkFabric{}

// NetworkFabric struct for NetworkFabric
type NetworkFabric struct {
	// The network fabric name
	Name string `json:"name"`
	// Network fabric description
	Description *string `json:"description,omitempty"`
	// The type of network fabric
	FabricType string `json:"fabricType"`
	FabricConfiguration NetworkFabricFabricConfiguration `json:"fabricConfiguration"`
	// Revision number of the entity
	Revision float32 `json:"revision"`
	// The network fabric ID.
	Id string `json:"id"`
	// Entity creation timestamp
	CreatedTimestamp time.Time `json:"createdTimestamp"`
	// Entity last update timestamp
	UpdatedTimestamp time.Time `json:"updatedTimestamp"`
	AdditionalProperties map[string]interface{}
}

type _NetworkFabric NetworkFabric

// NewNetworkFabric instantiates a new NetworkFabric object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkFabric(name string, fabricType string, fabricConfiguration NetworkFabricFabricConfiguration, revision float32, id string, createdTimestamp time.Time, updatedTimestamp time.Time) *NetworkFabric {
	this := NetworkFabric{}
	this.Name = name
	this.FabricType = fabricType
	this.FabricConfiguration = fabricConfiguration
	this.Revision = revision
	this.Id = id
	this.CreatedTimestamp = createdTimestamp
	this.UpdatedTimestamp = updatedTimestamp
	return &this
}

// NewNetworkFabricWithDefaults instantiates a new NetworkFabric object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkFabricWithDefaults() *NetworkFabric {
	this := NetworkFabric{}
	return &this
}

// GetName returns the Name field value
func (o *NetworkFabric) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworkFabric) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NetworkFabric) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NetworkFabric) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NetworkFabric) SetDescription(v string) {
	o.Description = &v
}

// GetFabricType returns the FabricType field value
func (o *NetworkFabric) GetFabricType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FabricType
}

// GetFabricTypeOk returns a tuple with the FabricType field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetFabricTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FabricType, true
}

// SetFabricType sets field value
func (o *NetworkFabric) SetFabricType(v string) {
	o.FabricType = v
}

// GetFabricConfiguration returns the FabricConfiguration field value
func (o *NetworkFabric) GetFabricConfiguration() NetworkFabricFabricConfiguration {
	if o == nil {
		var ret NetworkFabricFabricConfiguration
		return ret
	}

	return o.FabricConfiguration
}

// GetFabricConfigurationOk returns a tuple with the FabricConfiguration field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetFabricConfigurationOk() (*NetworkFabricFabricConfiguration, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FabricConfiguration, true
}

// SetFabricConfiguration sets field value
func (o *NetworkFabric) SetFabricConfiguration(v NetworkFabricFabricConfiguration) {
	o.FabricConfiguration = v
}

// GetRevision returns the Revision field value
func (o *NetworkFabric) GetRevision() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetRevisionOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *NetworkFabric) SetRevision(v float32) {
	o.Revision = v
}

// GetId returns the Id field value
func (o *NetworkFabric) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NetworkFabric) SetId(v string) {
	o.Id = v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value
func (o *NetworkFabric) GetCreatedTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetCreatedTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTimestamp, true
}

// SetCreatedTimestamp sets field value
func (o *NetworkFabric) SetCreatedTimestamp(v time.Time) {
	o.CreatedTimestamp = v
}

// GetUpdatedTimestamp returns the UpdatedTimestamp field value
func (o *NetworkFabric) GetUpdatedTimestamp() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedTimestamp
}

// GetUpdatedTimestampOk returns a tuple with the UpdatedTimestamp field value
// and a boolean to check if the value has been set.
func (o *NetworkFabric) GetUpdatedTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedTimestamp, true
}

// SetUpdatedTimestamp sets field value
func (o *NetworkFabric) SetUpdatedTimestamp(v time.Time) {
	o.UpdatedTimestamp = v
}

func (o NetworkFabric) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkFabric) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["fabricType"] = o.FabricType
	toSerialize["fabricConfiguration"] = o.FabricConfiguration
	toSerialize["revision"] = o.Revision
	toSerialize["id"] = o.Id
	toSerialize["createdTimestamp"] = o.CreatedTimestamp
	toSerialize["updatedTimestamp"] = o.UpdatedTimestamp

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkFabric) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"fabricType",
		"fabricConfiguration",
		"revision",
		"id",
		"createdTimestamp",
		"updatedTimestamp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkFabric := _NetworkFabric{}

	err = json.Unmarshal(data, &varNetworkFabric)

	if err != nil {
		return err
	}

	*o = NetworkFabric(varNetworkFabric)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "fabricType")
		delete(additionalProperties, "fabricConfiguration")
		delete(additionalProperties, "revision")
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdTimestamp")
		delete(additionalProperties, "updatedTimestamp")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkFabric struct {
	value *NetworkFabric
	isSet bool
}

func (v NullableNetworkFabric) Get() *NetworkFabric {
	return v.value
}

func (v *NullableNetworkFabric) Set(val *NetworkFabric) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkFabric) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkFabric) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkFabric(val *NetworkFabric) *NullableNetworkFabric {
	return &NullableNetworkFabric{value: val, isSet: true}
}

func (v NullableNetworkFabric) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkFabric) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


