/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the AuthConfigurationDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthConfigurationDto{}

// AuthConfigurationDto struct for AuthConfigurationDto
type AuthConfigurationDto struct {
	// User management and authentication provider settings
	Users *UsersDto `json:"users,omitempty"`
	// LDAP directory integration settings
	Ldap *LdapDto `json:"ldap,omitempty"`
	// SAML SSO integration settings
	Saml *SamlDto `json:"saml,omitempty"`
	// OAuth/OIDC token verification settings
	Oauth *OauthDto `json:"oauth,omitempty"`
	// Connected microservices configuration
	Microservices *AuthMicroservicesDto `json:"microservices,omitempty"`
	// Permissions automatically granted to OAuth token holders regardless of their token scopes
	OauthWhitelistedPermissions []string `json:"oauthWhitelistedPermissions,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AuthConfigurationDto AuthConfigurationDto

// NewAuthConfigurationDto instantiates a new AuthConfigurationDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthConfigurationDto() *AuthConfigurationDto {
	this := AuthConfigurationDto{}
	return &this
}

// NewAuthConfigurationDtoWithDefaults instantiates a new AuthConfigurationDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthConfigurationDtoWithDefaults() *AuthConfigurationDto {
	this := AuthConfigurationDto{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *AuthConfigurationDto) GetUsers() UsersDto {
	if o == nil || IsNil(o.Users) {
		var ret UsersDto
		return ret
	}
	return *o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfigurationDto) GetUsersOk() (*UsersDto, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *AuthConfigurationDto) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given UsersDto and assigns it to the Users field.
func (o *AuthConfigurationDto) SetUsers(v UsersDto) {
	o.Users = &v
}

// GetLdap returns the Ldap field value if set, zero value otherwise.
func (o *AuthConfigurationDto) GetLdap() LdapDto {
	if o == nil || IsNil(o.Ldap) {
		var ret LdapDto
		return ret
	}
	return *o.Ldap
}

// GetLdapOk returns a tuple with the Ldap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfigurationDto) GetLdapOk() (*LdapDto, bool) {
	if o == nil || IsNil(o.Ldap) {
		return nil, false
	}
	return o.Ldap, true
}

// HasLdap returns a boolean if a field has been set.
func (o *AuthConfigurationDto) HasLdap() bool {
	if o != nil && !IsNil(o.Ldap) {
		return true
	}

	return false
}

// SetLdap gets a reference to the given LdapDto and assigns it to the Ldap field.
func (o *AuthConfigurationDto) SetLdap(v LdapDto) {
	o.Ldap = &v
}

// GetSaml returns the Saml field value if set, zero value otherwise.
func (o *AuthConfigurationDto) GetSaml() SamlDto {
	if o == nil || IsNil(o.Saml) {
		var ret SamlDto
		return ret
	}
	return *o.Saml
}

// GetSamlOk returns a tuple with the Saml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfigurationDto) GetSamlOk() (*SamlDto, bool) {
	if o == nil || IsNil(o.Saml) {
		return nil, false
	}
	return o.Saml, true
}

// HasSaml returns a boolean if a field has been set.
func (o *AuthConfigurationDto) HasSaml() bool {
	if o != nil && !IsNil(o.Saml) {
		return true
	}

	return false
}

// SetSaml gets a reference to the given SamlDto and assigns it to the Saml field.
func (o *AuthConfigurationDto) SetSaml(v SamlDto) {
	o.Saml = &v
}

// GetOauth returns the Oauth field value if set, zero value otherwise.
func (o *AuthConfigurationDto) GetOauth() OauthDto {
	if o == nil || IsNil(o.Oauth) {
		var ret OauthDto
		return ret
	}
	return *o.Oauth
}

// GetOauthOk returns a tuple with the Oauth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfigurationDto) GetOauthOk() (*OauthDto, bool) {
	if o == nil || IsNil(o.Oauth) {
		return nil, false
	}
	return o.Oauth, true
}

// HasOauth returns a boolean if a field has been set.
func (o *AuthConfigurationDto) HasOauth() bool {
	if o != nil && !IsNil(o.Oauth) {
		return true
	}

	return false
}

// SetOauth gets a reference to the given OauthDto and assigns it to the Oauth field.
func (o *AuthConfigurationDto) SetOauth(v OauthDto) {
	o.Oauth = &v
}

// GetMicroservices returns the Microservices field value if set, zero value otherwise.
func (o *AuthConfigurationDto) GetMicroservices() AuthMicroservicesDto {
	if o == nil || IsNil(o.Microservices) {
		var ret AuthMicroservicesDto
		return ret
	}
	return *o.Microservices
}

// GetMicroservicesOk returns a tuple with the Microservices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfigurationDto) GetMicroservicesOk() (*AuthMicroservicesDto, bool) {
	if o == nil || IsNil(o.Microservices) {
		return nil, false
	}
	return o.Microservices, true
}

// HasMicroservices returns a boolean if a field has been set.
func (o *AuthConfigurationDto) HasMicroservices() bool {
	if o != nil && !IsNil(o.Microservices) {
		return true
	}

	return false
}

// SetMicroservices gets a reference to the given AuthMicroservicesDto and assigns it to the Microservices field.
func (o *AuthConfigurationDto) SetMicroservices(v AuthMicroservicesDto) {
	o.Microservices = &v
}

// GetOauthWhitelistedPermissions returns the OauthWhitelistedPermissions field value if set, zero value otherwise.
func (o *AuthConfigurationDto) GetOauthWhitelistedPermissions() []string {
	if o == nil || IsNil(o.OauthWhitelistedPermissions) {
		var ret []string
		return ret
	}
	return o.OauthWhitelistedPermissions
}

// GetOauthWhitelistedPermissionsOk returns a tuple with the OauthWhitelistedPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthConfigurationDto) GetOauthWhitelistedPermissionsOk() ([]string, bool) {
	if o == nil || IsNil(o.OauthWhitelistedPermissions) {
		return nil, false
	}
	return o.OauthWhitelistedPermissions, true
}

// HasOauthWhitelistedPermissions returns a boolean if a field has been set.
func (o *AuthConfigurationDto) HasOauthWhitelistedPermissions() bool {
	if o != nil && !IsNil(o.OauthWhitelistedPermissions) {
		return true
	}

	return false
}

// SetOauthWhitelistedPermissions gets a reference to the given []string and assigns it to the OauthWhitelistedPermissions field.
func (o *AuthConfigurationDto) SetOauthWhitelistedPermissions(v []string) {
	o.OauthWhitelistedPermissions = v
}

func (o AuthConfigurationDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthConfigurationDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Ldap) {
		toSerialize["ldap"] = o.Ldap
	}
	if !IsNil(o.Saml) {
		toSerialize["saml"] = o.Saml
	}
	if !IsNil(o.Oauth) {
		toSerialize["oauth"] = o.Oauth
	}
	if !IsNil(o.Microservices) {
		toSerialize["microservices"] = o.Microservices
	}
	if !IsNil(o.OauthWhitelistedPermissions) {
		toSerialize["oauthWhitelistedPermissions"] = o.OauthWhitelistedPermissions
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AuthConfigurationDto) UnmarshalJSON(data []byte) (err error) {
	varAuthConfigurationDto := _AuthConfigurationDto{}

	err = json.Unmarshal(data, &varAuthConfigurationDto)

	if err != nil {
		return err
	}

	*o = AuthConfigurationDto(varAuthConfigurationDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "users")
		delete(additionalProperties, "ldap")
		delete(additionalProperties, "saml")
		delete(additionalProperties, "oauth")
		delete(additionalProperties, "microservices")
		delete(additionalProperties, "oauthWhitelistedPermissions")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAuthConfigurationDto struct {
	value *AuthConfigurationDto
	isSet bool
}

func (v NullableAuthConfigurationDto) Get() *AuthConfigurationDto {
	return v.value
}

func (v *NullableAuthConfigurationDto) Set(val *AuthConfigurationDto) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthConfigurationDto) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthConfigurationDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthConfigurationDto(val *AuthConfigurationDto) *NullableAuthConfigurationDto {
	return &NullableAuthConfigurationDto{value: val, isSet: true}
}

func (v NullableAuthConfigurationDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthConfigurationDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


