/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the NotificationConfiguration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationConfiguration{}

// NotificationConfiguration struct for NotificationConfiguration
type NotificationConfiguration struct {
	// Syslog notification rules for email alerting
	SyslogNotificationRules []SyslogRule `json:"syslog_notification_rules,omitempty"`
	// Email addresses to notify about server health events
	ServerHealthNotificationEmails []string `json:"server_health_notification_emails,omitempty"`
	// Email addresses to notify about network device health events
	NetworkDeviceHealthNotificationEmails []string `json:"network_device_health_notification_emails,omitempty"`
	// Email addresses to notify about network device configuration drift
	NetworkDeviceConfigurationDriftNotificationEmails []string `json:"network_device_configuration_drift_notification_emails,omitempty"`
	// Email addresses to notify about VM pool health events
	VmPoolHealthNotificationEmails []string `json:"vm_pool_health_notification_emails,omitempty"`
	// Event retention policy configuration
	EventRetention map[string]interface{} `json:"eventRetention,omitempty"`
	// Time-to-live for buffered syslog messages in milliseconds
	SyslogBufferTtlMs *float32 `json:"syslog_buffer_ttl_ms,omitempty"`
	// Maximum number of unique syslog messages to buffer before flushing
	SyslogBufferMaxUnique *float32 `json:"syslog_buffer_max_unique,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NotificationConfiguration NotificationConfiguration

// NewNotificationConfiguration instantiates a new NotificationConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationConfiguration() *NotificationConfiguration {
	this := NotificationConfiguration{}
	return &this
}

// NewNotificationConfigurationWithDefaults instantiates a new NotificationConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationConfigurationWithDefaults() *NotificationConfiguration {
	this := NotificationConfiguration{}
	return &this
}

// GetSyslogNotificationRules returns the SyslogNotificationRules field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetSyslogNotificationRules() []SyslogRule {
	if o == nil || IsNil(o.SyslogNotificationRules) {
		var ret []SyslogRule
		return ret
	}
	return o.SyslogNotificationRules
}

// GetSyslogNotificationRulesOk returns a tuple with the SyslogNotificationRules field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetSyslogNotificationRulesOk() ([]SyslogRule, bool) {
	if o == nil || IsNil(o.SyslogNotificationRules) {
		return nil, false
	}
	return o.SyslogNotificationRules, true
}

// HasSyslogNotificationRules returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasSyslogNotificationRules() bool {
	if o != nil && !IsNil(o.SyslogNotificationRules) {
		return true
	}

	return false
}

// SetSyslogNotificationRules gets a reference to the given []SyslogRule and assigns it to the SyslogNotificationRules field.
func (o *NotificationConfiguration) SetSyslogNotificationRules(v []SyslogRule) {
	o.SyslogNotificationRules = v
}

// GetServerHealthNotificationEmails returns the ServerHealthNotificationEmails field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetServerHealthNotificationEmails() []string {
	if o == nil || IsNil(o.ServerHealthNotificationEmails) {
		var ret []string
		return ret
	}
	return o.ServerHealthNotificationEmails
}

// GetServerHealthNotificationEmailsOk returns a tuple with the ServerHealthNotificationEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetServerHealthNotificationEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.ServerHealthNotificationEmails) {
		return nil, false
	}
	return o.ServerHealthNotificationEmails, true
}

// HasServerHealthNotificationEmails returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasServerHealthNotificationEmails() bool {
	if o != nil && !IsNil(o.ServerHealthNotificationEmails) {
		return true
	}

	return false
}

// SetServerHealthNotificationEmails gets a reference to the given []string and assigns it to the ServerHealthNotificationEmails field.
func (o *NotificationConfiguration) SetServerHealthNotificationEmails(v []string) {
	o.ServerHealthNotificationEmails = v
}

// GetNetworkDeviceHealthNotificationEmails returns the NetworkDeviceHealthNotificationEmails field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetNetworkDeviceHealthNotificationEmails() []string {
	if o == nil || IsNil(o.NetworkDeviceHealthNotificationEmails) {
		var ret []string
		return ret
	}
	return o.NetworkDeviceHealthNotificationEmails
}

// GetNetworkDeviceHealthNotificationEmailsOk returns a tuple with the NetworkDeviceHealthNotificationEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetNetworkDeviceHealthNotificationEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.NetworkDeviceHealthNotificationEmails) {
		return nil, false
	}
	return o.NetworkDeviceHealthNotificationEmails, true
}

// HasNetworkDeviceHealthNotificationEmails returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasNetworkDeviceHealthNotificationEmails() bool {
	if o != nil && !IsNil(o.NetworkDeviceHealthNotificationEmails) {
		return true
	}

	return false
}

// SetNetworkDeviceHealthNotificationEmails gets a reference to the given []string and assigns it to the NetworkDeviceHealthNotificationEmails field.
func (o *NotificationConfiguration) SetNetworkDeviceHealthNotificationEmails(v []string) {
	o.NetworkDeviceHealthNotificationEmails = v
}

// GetNetworkDeviceConfigurationDriftNotificationEmails returns the NetworkDeviceConfigurationDriftNotificationEmails field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetNetworkDeviceConfigurationDriftNotificationEmails() []string {
	if o == nil || IsNil(o.NetworkDeviceConfigurationDriftNotificationEmails) {
		var ret []string
		return ret
	}
	return o.NetworkDeviceConfigurationDriftNotificationEmails
}

// GetNetworkDeviceConfigurationDriftNotificationEmailsOk returns a tuple with the NetworkDeviceConfigurationDriftNotificationEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetNetworkDeviceConfigurationDriftNotificationEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.NetworkDeviceConfigurationDriftNotificationEmails) {
		return nil, false
	}
	return o.NetworkDeviceConfigurationDriftNotificationEmails, true
}

// HasNetworkDeviceConfigurationDriftNotificationEmails returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasNetworkDeviceConfigurationDriftNotificationEmails() bool {
	if o != nil && !IsNil(o.NetworkDeviceConfigurationDriftNotificationEmails) {
		return true
	}

	return false
}

// SetNetworkDeviceConfigurationDriftNotificationEmails gets a reference to the given []string and assigns it to the NetworkDeviceConfigurationDriftNotificationEmails field.
func (o *NotificationConfiguration) SetNetworkDeviceConfigurationDriftNotificationEmails(v []string) {
	o.NetworkDeviceConfigurationDriftNotificationEmails = v
}

// GetVmPoolHealthNotificationEmails returns the VmPoolHealthNotificationEmails field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetVmPoolHealthNotificationEmails() []string {
	if o == nil || IsNil(o.VmPoolHealthNotificationEmails) {
		var ret []string
		return ret
	}
	return o.VmPoolHealthNotificationEmails
}

// GetVmPoolHealthNotificationEmailsOk returns a tuple with the VmPoolHealthNotificationEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetVmPoolHealthNotificationEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.VmPoolHealthNotificationEmails) {
		return nil, false
	}
	return o.VmPoolHealthNotificationEmails, true
}

// HasVmPoolHealthNotificationEmails returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasVmPoolHealthNotificationEmails() bool {
	if o != nil && !IsNil(o.VmPoolHealthNotificationEmails) {
		return true
	}

	return false
}

// SetVmPoolHealthNotificationEmails gets a reference to the given []string and assigns it to the VmPoolHealthNotificationEmails field.
func (o *NotificationConfiguration) SetVmPoolHealthNotificationEmails(v []string) {
	o.VmPoolHealthNotificationEmails = v
}

// GetEventRetention returns the EventRetention field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetEventRetention() map[string]interface{} {
	if o == nil || IsNil(o.EventRetention) {
		var ret map[string]interface{}
		return ret
	}
	return o.EventRetention
}

// GetEventRetentionOk returns a tuple with the EventRetention field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetEventRetentionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.EventRetention) {
		return map[string]interface{}{}, false
	}
	return o.EventRetention, true
}

// HasEventRetention returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasEventRetention() bool {
	if o != nil && !IsNil(o.EventRetention) {
		return true
	}

	return false
}

// SetEventRetention gets a reference to the given map[string]interface{} and assigns it to the EventRetention field.
func (o *NotificationConfiguration) SetEventRetention(v map[string]interface{}) {
	o.EventRetention = v
}

// GetSyslogBufferTtlMs returns the SyslogBufferTtlMs field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetSyslogBufferTtlMs() float32 {
	if o == nil || IsNil(o.SyslogBufferTtlMs) {
		var ret float32
		return ret
	}
	return *o.SyslogBufferTtlMs
}

// GetSyslogBufferTtlMsOk returns a tuple with the SyslogBufferTtlMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetSyslogBufferTtlMsOk() (*float32, bool) {
	if o == nil || IsNil(o.SyslogBufferTtlMs) {
		return nil, false
	}
	return o.SyslogBufferTtlMs, true
}

// HasSyslogBufferTtlMs returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasSyslogBufferTtlMs() bool {
	if o != nil && !IsNil(o.SyslogBufferTtlMs) {
		return true
	}

	return false
}

// SetSyslogBufferTtlMs gets a reference to the given float32 and assigns it to the SyslogBufferTtlMs field.
func (o *NotificationConfiguration) SetSyslogBufferTtlMs(v float32) {
	o.SyslogBufferTtlMs = &v
}

// GetSyslogBufferMaxUnique returns the SyslogBufferMaxUnique field value if set, zero value otherwise.
func (o *NotificationConfiguration) GetSyslogBufferMaxUnique() float32 {
	if o == nil || IsNil(o.SyslogBufferMaxUnique) {
		var ret float32
		return ret
	}
	return *o.SyslogBufferMaxUnique
}

// GetSyslogBufferMaxUniqueOk returns a tuple with the SyslogBufferMaxUnique field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationConfiguration) GetSyslogBufferMaxUniqueOk() (*float32, bool) {
	if o == nil || IsNil(o.SyslogBufferMaxUnique) {
		return nil, false
	}
	return o.SyslogBufferMaxUnique, true
}

// HasSyslogBufferMaxUnique returns a boolean if a field has been set.
func (o *NotificationConfiguration) HasSyslogBufferMaxUnique() bool {
	if o != nil && !IsNil(o.SyslogBufferMaxUnique) {
		return true
	}

	return false
}

// SetSyslogBufferMaxUnique gets a reference to the given float32 and assigns it to the SyslogBufferMaxUnique field.
func (o *NotificationConfiguration) SetSyslogBufferMaxUnique(v float32) {
	o.SyslogBufferMaxUnique = &v
}

func (o NotificationConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationConfiguration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SyslogNotificationRules) {
		toSerialize["syslog_notification_rules"] = o.SyslogNotificationRules
	}
	if !IsNil(o.ServerHealthNotificationEmails) {
		toSerialize["server_health_notification_emails"] = o.ServerHealthNotificationEmails
	}
	if !IsNil(o.NetworkDeviceHealthNotificationEmails) {
		toSerialize["network_device_health_notification_emails"] = o.NetworkDeviceHealthNotificationEmails
	}
	if !IsNil(o.NetworkDeviceConfigurationDriftNotificationEmails) {
		toSerialize["network_device_configuration_drift_notification_emails"] = o.NetworkDeviceConfigurationDriftNotificationEmails
	}
	if !IsNil(o.VmPoolHealthNotificationEmails) {
		toSerialize["vm_pool_health_notification_emails"] = o.VmPoolHealthNotificationEmails
	}
	if !IsNil(o.EventRetention) {
		toSerialize["eventRetention"] = o.EventRetention
	}
	if !IsNil(o.SyslogBufferTtlMs) {
		toSerialize["syslog_buffer_ttl_ms"] = o.SyslogBufferTtlMs
	}
	if !IsNil(o.SyslogBufferMaxUnique) {
		toSerialize["syslog_buffer_max_unique"] = o.SyslogBufferMaxUnique
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NotificationConfiguration) UnmarshalJSON(data []byte) (err error) {
	varNotificationConfiguration := _NotificationConfiguration{}

	err = json.Unmarshal(data, &varNotificationConfiguration)

	if err != nil {
		return err
	}

	*o = NotificationConfiguration(varNotificationConfiguration)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "syslog_notification_rules")
		delete(additionalProperties, "server_health_notification_emails")
		delete(additionalProperties, "network_device_health_notification_emails")
		delete(additionalProperties, "network_device_configuration_drift_notification_emails")
		delete(additionalProperties, "vm_pool_health_notification_emails")
		delete(additionalProperties, "eventRetention")
		delete(additionalProperties, "syslog_buffer_ttl_ms")
		delete(additionalProperties, "syslog_buffer_max_unique")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNotificationConfiguration struct {
	value *NotificationConfiguration
	isSet bool
}

func (v NullableNotificationConfiguration) Get() *NotificationConfiguration {
	return v.value
}

func (v *NullableNotificationConfiguration) Set(val *NotificationConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationConfiguration(val *NotificationConfiguration) *NullableNotificationConfiguration {
	return &NullableNotificationConfiguration{value: val, isSet: true}
}

func (v NullableNotificationConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


