/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the PointToPointInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointToPointInterface{}

// PointToPointInterface struct for PointToPointInterface
type PointToPointInterface struct {
	Type PointToPointInterfaceType `json:"type"`
	InterfaceId int64 `json:"interfaceId"`
	AdditionalProperties map[string]interface{}
}

type _PointToPointInterface PointToPointInterface

// NewPointToPointInterface instantiates a new PointToPointInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointToPointInterface(type_ PointToPointInterfaceType, interfaceId int64) *PointToPointInterface {
	this := PointToPointInterface{}
	this.Type = type_
	this.InterfaceId = interfaceId
	return &this
}

// NewPointToPointInterfaceWithDefaults instantiates a new PointToPointInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointToPointInterfaceWithDefaults() *PointToPointInterface {
	this := PointToPointInterface{}
	return &this
}

// GetType returns the Type field value
func (o *PointToPointInterface) GetType() PointToPointInterfaceType {
	if o == nil {
		var ret PointToPointInterfaceType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PointToPointInterface) GetTypeOk() (*PointToPointInterfaceType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PointToPointInterface) SetType(v PointToPointInterfaceType) {
	o.Type = v
}

// GetInterfaceId returns the InterfaceId field value
func (o *PointToPointInterface) GetInterfaceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.InterfaceId
}

// GetInterfaceIdOk returns a tuple with the InterfaceId field value
// and a boolean to check if the value has been set.
func (o *PointToPointInterface) GetInterfaceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InterfaceId, true
}

// SetInterfaceId sets field value
func (o *PointToPointInterface) SetInterfaceId(v int64) {
	o.InterfaceId = v
}

func (o PointToPointInterface) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointToPointInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["interfaceId"] = o.InterfaceId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PointToPointInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"interfaceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointToPointInterface := _PointToPointInterface{}

	err = json.Unmarshal(data, &varPointToPointInterface)

	if err != nil {
		return err
	}

	*o = PointToPointInterface(varPointToPointInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "type")
		delete(additionalProperties, "interfaceId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePointToPointInterface struct {
	value *PointToPointInterface
	isSet bool
}

func (v NullablePointToPointInterface) Get() *PointToPointInterface {
	return v.value
}

func (v *NullablePointToPointInterface) Set(val *PointToPointInterface) {
	v.value = val
	v.isSet = true
}

func (v NullablePointToPointInterface) IsSet() bool {
	return v.isSet
}

func (v *NullablePointToPointInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointToPointInterface(val *PointToPointInterface) *NullablePointToPointInterface {
	return &NullablePointToPointInterface{value: val, isSet: true}
}

func (v NullablePointToPointInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointToPointInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


