/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateVxlanLogicalNetworkIpv4Properties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVxlanLogicalNetworkIpv4Properties{}

// CreateVxlanLogicalNetworkIpv4Properties struct for CreateVxlanLogicalNetworkIpv4Properties
type CreateVxlanLogicalNetworkIpv4Properties struct {
	SubnetAllocationStrategies []CreateIpv4SubnetAllocationStrategy1 `json:"subnetAllocationStrategies"`
	AdditionalProperties map[string]interface{}
}

type _CreateVxlanLogicalNetworkIpv4Properties CreateVxlanLogicalNetworkIpv4Properties

// NewCreateVxlanLogicalNetworkIpv4Properties instantiates a new CreateVxlanLogicalNetworkIpv4Properties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVxlanLogicalNetworkIpv4Properties(subnetAllocationStrategies []CreateIpv4SubnetAllocationStrategy1) *CreateVxlanLogicalNetworkIpv4Properties {
	this := CreateVxlanLogicalNetworkIpv4Properties{}
	this.SubnetAllocationStrategies = subnetAllocationStrategies
	return &this
}

// NewCreateVxlanLogicalNetworkIpv4PropertiesWithDefaults instantiates a new CreateVxlanLogicalNetworkIpv4Properties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVxlanLogicalNetworkIpv4PropertiesWithDefaults() *CreateVxlanLogicalNetworkIpv4Properties {
	this := CreateVxlanLogicalNetworkIpv4Properties{}
	return &this
}

// GetSubnetAllocationStrategies returns the SubnetAllocationStrategies field value
func (o *CreateVxlanLogicalNetworkIpv4Properties) GetSubnetAllocationStrategies() []CreateIpv4SubnetAllocationStrategy1 {
	if o == nil {
		var ret []CreateIpv4SubnetAllocationStrategy1
		return ret
	}

	return o.SubnetAllocationStrategies
}

// GetSubnetAllocationStrategiesOk returns a tuple with the SubnetAllocationStrategies field value
// and a boolean to check if the value has been set.
func (o *CreateVxlanLogicalNetworkIpv4Properties) GetSubnetAllocationStrategiesOk() ([]CreateIpv4SubnetAllocationStrategy1, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetAllocationStrategies, true
}

// SetSubnetAllocationStrategies sets field value
func (o *CreateVxlanLogicalNetworkIpv4Properties) SetSubnetAllocationStrategies(v []CreateIpv4SubnetAllocationStrategy1) {
	o.SubnetAllocationStrategies = v
}

func (o CreateVxlanLogicalNetworkIpv4Properties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVxlanLogicalNetworkIpv4Properties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subnetAllocationStrategies"] = o.SubnetAllocationStrategies

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateVxlanLogicalNetworkIpv4Properties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subnetAllocationStrategies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateVxlanLogicalNetworkIpv4Properties := _CreateVxlanLogicalNetworkIpv4Properties{}

	err = json.Unmarshal(data, &varCreateVxlanLogicalNetworkIpv4Properties)

	if err != nil {
		return err
	}

	*o = CreateVxlanLogicalNetworkIpv4Properties(varCreateVxlanLogicalNetworkIpv4Properties)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subnetAllocationStrategies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateVxlanLogicalNetworkIpv4Properties struct {
	value *CreateVxlanLogicalNetworkIpv4Properties
	isSet bool
}

func (v NullableCreateVxlanLogicalNetworkIpv4Properties) Get() *CreateVxlanLogicalNetworkIpv4Properties {
	return v.value
}

func (v *NullableCreateVxlanLogicalNetworkIpv4Properties) Set(val *CreateVxlanLogicalNetworkIpv4Properties) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVxlanLogicalNetworkIpv4Properties) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVxlanLogicalNetworkIpv4Properties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVxlanLogicalNetworkIpv4Properties(val *CreateVxlanLogicalNetworkIpv4Properties) *NullableCreateVxlanLogicalNetworkIpv4Properties {
	return &NullableCreateVxlanLogicalNetworkIpv4Properties{value: val, isSet: true}
}

func (v NullableCreateVxlanLogicalNetworkIpv4Properties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVxlanLogicalNetworkIpv4Properties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


