/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the AutoVniAllocationStrategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AutoVniAllocationStrategy{}

// AutoVniAllocationStrategy struct for AutoVniAllocationStrategy
type AutoVniAllocationStrategy struct {
	Id int32 `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	Kind AllocationStrategyKind `json:"kind"`
	Scope ResourceScope `json:"scope"`
	AdditionalProperties map[string]interface{}
}

type _AutoVniAllocationStrategy AutoVniAllocationStrategy

// NewAutoVniAllocationStrategy instantiates a new AutoVniAllocationStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAutoVniAllocationStrategy(id int32, createdAt time.Time, updatedAt time.Time, kind AllocationStrategyKind, scope ResourceScope) *AutoVniAllocationStrategy {
	this := AutoVniAllocationStrategy{}
	this.Id = id
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Kind = kind
	this.Scope = scope
	return &this
}

// NewAutoVniAllocationStrategyWithDefaults instantiates a new AutoVniAllocationStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAutoVniAllocationStrategyWithDefaults() *AutoVniAllocationStrategy {
	this := AutoVniAllocationStrategy{}
	return &this
}

// GetId returns the Id field value
func (o *AutoVniAllocationStrategy) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AutoVniAllocationStrategy) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AutoVniAllocationStrategy) SetId(v int32) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *AutoVniAllocationStrategy) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *AutoVniAllocationStrategy) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *AutoVniAllocationStrategy) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AutoVniAllocationStrategy) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AutoVniAllocationStrategy) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AutoVniAllocationStrategy) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetKind returns the Kind field value
func (o *AutoVniAllocationStrategy) GetKind() AllocationStrategyKind {
	if o == nil {
		var ret AllocationStrategyKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AutoVniAllocationStrategy) GetKindOk() (*AllocationStrategyKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AutoVniAllocationStrategy) SetKind(v AllocationStrategyKind) {
	o.Kind = v
}

// GetScope returns the Scope field value
func (o *AutoVniAllocationStrategy) GetScope() ResourceScope {
	if o == nil {
		var ret ResourceScope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *AutoVniAllocationStrategy) GetScopeOk() (*ResourceScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *AutoVniAllocationStrategy) SetScope(v ResourceScope) {
	o.Scope = v
}

func (o AutoVniAllocationStrategy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AutoVniAllocationStrategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["kind"] = o.Kind
	toSerialize["scope"] = o.Scope

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AutoVniAllocationStrategy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"createdAt",
		"updatedAt",
		"kind",
		"scope",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAutoVniAllocationStrategy := _AutoVniAllocationStrategy{}

	err = json.Unmarshal(data, &varAutoVniAllocationStrategy)

	if err != nil {
		return err
	}

	*o = AutoVniAllocationStrategy(varAutoVniAllocationStrategy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "scope")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAutoVniAllocationStrategy struct {
	value *AutoVniAllocationStrategy
	isSet bool
}

func (v NullableAutoVniAllocationStrategy) Get() *AutoVniAllocationStrategy {
	return v.value
}

func (v *NullableAutoVniAllocationStrategy) Set(val *AutoVniAllocationStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullableAutoVniAllocationStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullableAutoVniAllocationStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAutoVniAllocationStrategy(val *AutoVniAllocationStrategy) *NullableAutoVniAllocationStrategy {
	return &NullableAutoVniAllocationStrategy{value: val, isSet: true}
}

func (v NullableAutoVniAllocationStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAutoVniAllocationStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


