/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the NetworkEndpointGroupPaginatedList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkEndpointGroupPaginatedList{}

// NetworkEndpointGroupPaginatedList struct for NetworkEndpointGroupPaginatedList
type NetworkEndpointGroupPaginatedList struct {
	Data []NetworkEndpointGroup `json:"data"`
	// Metadata about the pagination of the response
	Meta PaginatedResponseMeta `json:"meta"`
	// Links to navigate through the paginated results
	Links *PaginatedResponseLinks `json:"links,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NetworkEndpointGroupPaginatedList NetworkEndpointGroupPaginatedList

// NewNetworkEndpointGroupPaginatedList instantiates a new NetworkEndpointGroupPaginatedList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkEndpointGroupPaginatedList(data []NetworkEndpointGroup, meta PaginatedResponseMeta) *NetworkEndpointGroupPaginatedList {
	this := NetworkEndpointGroupPaginatedList{}
	this.Data = data
	this.Meta = meta
	return &this
}

// NewNetworkEndpointGroupPaginatedListWithDefaults instantiates a new NetworkEndpointGroupPaginatedList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkEndpointGroupPaginatedListWithDefaults() *NetworkEndpointGroupPaginatedList {
	this := NetworkEndpointGroupPaginatedList{}
	return &this
}

// GetData returns the Data field value
func (o *NetworkEndpointGroupPaginatedList) GetData() []NetworkEndpointGroup {
	if o == nil {
		var ret []NetworkEndpointGroup
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *NetworkEndpointGroupPaginatedList) GetDataOk() ([]NetworkEndpointGroup, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *NetworkEndpointGroupPaginatedList) SetData(v []NetworkEndpointGroup) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *NetworkEndpointGroupPaginatedList) GetMeta() PaginatedResponseMeta {
	if o == nil {
		var ret PaginatedResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *NetworkEndpointGroupPaginatedList) GetMetaOk() (*PaginatedResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *NetworkEndpointGroupPaginatedList) SetMeta(v PaginatedResponseMeta) {
	o.Meta = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *NetworkEndpointGroupPaginatedList) GetLinks() PaginatedResponseLinks {
	if o == nil || IsNil(o.Links) {
		var ret PaginatedResponseLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkEndpointGroupPaginatedList) GetLinksOk() (*PaginatedResponseLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *NetworkEndpointGroupPaginatedList) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given PaginatedResponseLinks and assigns it to the Links field.
func (o *NetworkEndpointGroupPaginatedList) SetLinks(v PaginatedResponseLinks) {
	o.Links = &v
}

func (o NetworkEndpointGroupPaginatedList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkEndpointGroupPaginatedList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NetworkEndpointGroupPaginatedList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"meta",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworkEndpointGroupPaginatedList := _NetworkEndpointGroupPaginatedList{}

	err = json.Unmarshal(data, &varNetworkEndpointGroupPaginatedList)

	if err != nil {
		return err
	}

	*o = NetworkEndpointGroupPaginatedList(varNetworkEndpointGroupPaginatedList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNetworkEndpointGroupPaginatedList struct {
	value *NetworkEndpointGroupPaginatedList
	isSet bool
}

func (v NullableNetworkEndpointGroupPaginatedList) Get() *NetworkEndpointGroupPaginatedList {
	return v.value
}

func (v *NullableNetworkEndpointGroupPaginatedList) Set(val *NetworkEndpointGroupPaginatedList) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkEndpointGroupPaginatedList) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkEndpointGroupPaginatedList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkEndpointGroupPaginatedList(val *NetworkEndpointGroupPaginatedList) *NullableNetworkEndpointGroupPaginatedList {
	return &NullableNetworkEndpointGroupPaginatedList{value: val, isSet: true}
}

func (v NullableNetworkEndpointGroupPaginatedList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkEndpointGroupPaginatedList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


