/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedZoneAllocationStrategy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedZoneAllocationStrategy{}

// PaginatedZoneAllocationStrategy struct for PaginatedZoneAllocationStrategy
type PaginatedZoneAllocationStrategy struct {
	Data []ZoneAllocationStrategy `json:"data"`
	// Metadata about the pagination of the response
	Meta PaginatedResponseMeta `json:"meta"`
	// Links to navigate through the paginated results
	Links PaginatedResponseLinks `json:"links"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedZoneAllocationStrategy PaginatedZoneAllocationStrategy

// NewPaginatedZoneAllocationStrategy instantiates a new PaginatedZoneAllocationStrategy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedZoneAllocationStrategy(data []ZoneAllocationStrategy, meta PaginatedResponseMeta, links PaginatedResponseLinks) *PaginatedZoneAllocationStrategy {
	this := PaginatedZoneAllocationStrategy{}
	this.Data = data
	this.Meta = meta
	this.Links = links
	return &this
}

// NewPaginatedZoneAllocationStrategyWithDefaults instantiates a new PaginatedZoneAllocationStrategy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedZoneAllocationStrategyWithDefaults() *PaginatedZoneAllocationStrategy {
	this := PaginatedZoneAllocationStrategy{}
	return &this
}

// GetData returns the Data field value
func (o *PaginatedZoneAllocationStrategy) GetData() []ZoneAllocationStrategy {
	if o == nil {
		var ret []ZoneAllocationStrategy
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PaginatedZoneAllocationStrategy) GetDataOk() ([]ZoneAllocationStrategy, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *PaginatedZoneAllocationStrategy) SetData(v []ZoneAllocationStrategy) {
	o.Data = v
}

// GetMeta returns the Meta field value
func (o *PaginatedZoneAllocationStrategy) GetMeta() PaginatedResponseMeta {
	if o == nil {
		var ret PaginatedResponseMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *PaginatedZoneAllocationStrategy) GetMetaOk() (*PaginatedResponseMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *PaginatedZoneAllocationStrategy) SetMeta(v PaginatedResponseMeta) {
	o.Meta = v
}

// GetLinks returns the Links field value
func (o *PaginatedZoneAllocationStrategy) GetLinks() PaginatedResponseLinks {
	if o == nil {
		var ret PaginatedResponseLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *PaginatedZoneAllocationStrategy) GetLinksOk() (*PaginatedResponseLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *PaginatedZoneAllocationStrategy) SetLinks(v PaginatedResponseLinks) {
	o.Links = v
}

func (o PaginatedZoneAllocationStrategy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedZoneAllocationStrategy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["meta"] = o.Meta
	toSerialize["links"] = o.Links

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedZoneAllocationStrategy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"meta",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedZoneAllocationStrategy := _PaginatedZoneAllocationStrategy{}

	err = json.Unmarshal(data, &varPaginatedZoneAllocationStrategy)

	if err != nil {
		return err
	}

	*o = PaginatedZoneAllocationStrategy(varPaginatedZoneAllocationStrategy)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "links")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePaginatedZoneAllocationStrategy struct {
	value *PaginatedZoneAllocationStrategy
	isSet bool
}

func (v NullablePaginatedZoneAllocationStrategy) Get() *PaginatedZoneAllocationStrategy {
	return v.value
}

func (v *NullablePaginatedZoneAllocationStrategy) Set(val *PaginatedZoneAllocationStrategy) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedZoneAllocationStrategy) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedZoneAllocationStrategy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedZoneAllocationStrategy(val *PaginatedZoneAllocationStrategy) *NullablePaginatedZoneAllocationStrategy {
	return &NullablePaginatedZoneAllocationStrategy{value: val, isSet: true}
}

func (v NullablePaginatedZoneAllocationStrategy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedZoneAllocationStrategy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


