/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the PointToPointLinkConfigIpv6Properties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PointToPointLinkConfigIpv6Properties{}

// PointToPointLinkConfigIpv6Properties struct for PointToPointLinkConfigIpv6Properties
type PointToPointLinkConfigIpv6Properties struct {
	SubnetAllocationStrategies []CreatePointToPointLinkConfigIpv6SubnetAllocationStrategy201Response `json:"subnetAllocationStrategies"`
	// Staged IPv6 static routes.
	StaticRoutes []PointToPointStaticRoute `json:"staticRoutes"`
	AdditionalProperties map[string]interface{}
}

type _PointToPointLinkConfigIpv6Properties PointToPointLinkConfigIpv6Properties

// NewPointToPointLinkConfigIpv6Properties instantiates a new PointToPointLinkConfigIpv6Properties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPointToPointLinkConfigIpv6Properties(subnetAllocationStrategies []CreatePointToPointLinkConfigIpv6SubnetAllocationStrategy201Response, staticRoutes []PointToPointStaticRoute) *PointToPointLinkConfigIpv6Properties {
	this := PointToPointLinkConfigIpv6Properties{}
	this.SubnetAllocationStrategies = subnetAllocationStrategies
	this.StaticRoutes = staticRoutes
	return &this
}

// NewPointToPointLinkConfigIpv6PropertiesWithDefaults instantiates a new PointToPointLinkConfigIpv6Properties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPointToPointLinkConfigIpv6PropertiesWithDefaults() *PointToPointLinkConfigIpv6Properties {
	this := PointToPointLinkConfigIpv6Properties{}
	return &this
}

// GetSubnetAllocationStrategies returns the SubnetAllocationStrategies field value
func (o *PointToPointLinkConfigIpv6Properties) GetSubnetAllocationStrategies() []CreatePointToPointLinkConfigIpv6SubnetAllocationStrategy201Response {
	if o == nil {
		var ret []CreatePointToPointLinkConfigIpv6SubnetAllocationStrategy201Response
		return ret
	}

	return o.SubnetAllocationStrategies
}

// GetSubnetAllocationStrategiesOk returns a tuple with the SubnetAllocationStrategies field value
// and a boolean to check if the value has been set.
func (o *PointToPointLinkConfigIpv6Properties) GetSubnetAllocationStrategiesOk() ([]CreatePointToPointLinkConfigIpv6SubnetAllocationStrategy201Response, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetAllocationStrategies, true
}

// SetSubnetAllocationStrategies sets field value
func (o *PointToPointLinkConfigIpv6Properties) SetSubnetAllocationStrategies(v []CreatePointToPointLinkConfigIpv6SubnetAllocationStrategy201Response) {
	o.SubnetAllocationStrategies = v
}

// GetStaticRoutes returns the StaticRoutes field value
func (o *PointToPointLinkConfigIpv6Properties) GetStaticRoutes() []PointToPointStaticRoute {
	if o == nil {
		var ret []PointToPointStaticRoute
		return ret
	}

	return o.StaticRoutes
}

// GetStaticRoutesOk returns a tuple with the StaticRoutes field value
// and a boolean to check if the value has been set.
func (o *PointToPointLinkConfigIpv6Properties) GetStaticRoutesOk() ([]PointToPointStaticRoute, bool) {
	if o == nil {
		return nil, false
	}
	return o.StaticRoutes, true
}

// SetStaticRoutes sets field value
func (o *PointToPointLinkConfigIpv6Properties) SetStaticRoutes(v []PointToPointStaticRoute) {
	o.StaticRoutes = v
}

func (o PointToPointLinkConfigIpv6Properties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PointToPointLinkConfigIpv6Properties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subnetAllocationStrategies"] = o.SubnetAllocationStrategies
	toSerialize["staticRoutes"] = o.StaticRoutes

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PointToPointLinkConfigIpv6Properties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subnetAllocationStrategies",
		"staticRoutes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPointToPointLinkConfigIpv6Properties := _PointToPointLinkConfigIpv6Properties{}

	err = json.Unmarshal(data, &varPointToPointLinkConfigIpv6Properties)

	if err != nil {
		return err
	}

	*o = PointToPointLinkConfigIpv6Properties(varPointToPointLinkConfigIpv6Properties)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subnetAllocationStrategies")
		delete(additionalProperties, "staticRoutes")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePointToPointLinkConfigIpv6Properties struct {
	value *PointToPointLinkConfigIpv6Properties
	isSet bool
}

func (v NullablePointToPointLinkConfigIpv6Properties) Get() *PointToPointLinkConfigIpv6Properties {
	return v.value
}

func (v *NullablePointToPointLinkConfigIpv6Properties) Set(val *PointToPointLinkConfigIpv6Properties) {
	v.value = val
	v.isSet = true
}

func (v NullablePointToPointLinkConfigIpv6Properties) IsSet() bool {
	return v.isSet
}

func (v *NullablePointToPointLinkConfigIpv6Properties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePointToPointLinkConfigIpv6Properties(val *PointToPointLinkConfigIpv6Properties) *NullablePointToPointLinkConfigIpv6Properties {
	return &NullablePointToPointLinkConfigIpv6Properties{value: val, isSet: true}
}

func (v NullablePointToPointLinkConfigIpv6Properties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePointToPointLinkConfigIpv6Properties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


