/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the SetNetworkEquipmentInterfaceBreakout type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetNetworkEquipmentInterfaceBreakout{}

// SetNetworkEquipmentInterfaceBreakout struct for SetNetworkEquipmentInterfaceBreakout
type SetNetworkEquipmentInterfaceBreakout struct {
	// Breakout mode in \"<count>x<speed>G\" form (e.g. \"4x25G\", \"2x50G\", \"1x100G\").
	Mode string `json:"mode"`
	AdditionalProperties map[string]interface{}
}

type _SetNetworkEquipmentInterfaceBreakout SetNetworkEquipmentInterfaceBreakout

// NewSetNetworkEquipmentInterfaceBreakout instantiates a new SetNetworkEquipmentInterfaceBreakout object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetNetworkEquipmentInterfaceBreakout(mode string) *SetNetworkEquipmentInterfaceBreakout {
	this := SetNetworkEquipmentInterfaceBreakout{}
	this.Mode = mode
	return &this
}

// NewSetNetworkEquipmentInterfaceBreakoutWithDefaults instantiates a new SetNetworkEquipmentInterfaceBreakout object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetNetworkEquipmentInterfaceBreakoutWithDefaults() *SetNetworkEquipmentInterfaceBreakout {
	this := SetNetworkEquipmentInterfaceBreakout{}
	return &this
}

// GetMode returns the Mode field value
func (o *SetNetworkEquipmentInterfaceBreakout) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *SetNetworkEquipmentInterfaceBreakout) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *SetNetworkEquipmentInterfaceBreakout) SetMode(v string) {
	o.Mode = v
}

func (o SetNetworkEquipmentInterfaceBreakout) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetNetworkEquipmentInterfaceBreakout) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetNetworkEquipmentInterfaceBreakout) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetNetworkEquipmentInterfaceBreakout := _SetNetworkEquipmentInterfaceBreakout{}

	err = json.Unmarshal(data, &varSetNetworkEquipmentInterfaceBreakout)

	if err != nil {
		return err
	}

	*o = SetNetworkEquipmentInterfaceBreakout(varSetNetworkEquipmentInterfaceBreakout)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "mode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetNetworkEquipmentInterfaceBreakout struct {
	value *SetNetworkEquipmentInterfaceBreakout
	isSet bool
}

func (v NullableSetNetworkEquipmentInterfaceBreakout) Get() *SetNetworkEquipmentInterfaceBreakout {
	return v.value
}

func (v *NullableSetNetworkEquipmentInterfaceBreakout) Set(val *SetNetworkEquipmentInterfaceBreakout) {
	v.value = val
	v.isSet = true
}

func (v NullableSetNetworkEquipmentInterfaceBreakout) IsSet() bool {
	return v.isSet
}

func (v *NullableSetNetworkEquipmentInterfaceBreakout) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetNetworkEquipmentInterfaceBreakout(val *SetNetworkEquipmentInterfaceBreakout) *NullableSetNetworkEquipmentInterfaceBreakout {
	return &NullableSetNetworkEquipmentInterfaceBreakout{value: val, isSet: true}
}

func (v NullableSetNetworkEquipmentInterfaceBreakout) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetNetworkEquipmentInterfaceBreakout) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


