/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the LogicalNetworkInterconnect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogicalNetworkInterconnect{}

// LogicalNetworkInterconnect struct for LogicalNetworkInterconnect
type LogicalNetworkInterconnect struct {
	// Revision number of the entity
	Revision string `json:"revision"`
	// Unique identifier for the logical network interconnect
	Id string `json:"id"`
	// Unique label for the logical network interconnect
	Label string `json:"label"`
	// Name of the logical network interconnect
	Name string `json:"name"`
	// JSON object containing additional metadata or annotations
	Annotations *map[string]string `json:"annotations,omitempty"`
	// Kind of the logical network interconnect
	Kind LogicalNetworkInterconnectKind `json:"kind"`
	// Fabric Interconnect identifier
	FabricInterconnectId int32 `json:"fabricInterconnectId"`
	// Transport ID allocated from range 999999999-900000000 (descending)
	TransportId *int32 `json:"transportId,omitempty"`
	// Status of the logical network interconnect
	Status LogicalNetworkInterconnectStatus `json:"status"`
	// The date and time the entity was created
	CreatedAt time.Time `json:"createdAt"`
	// The date and time the entity was last updated
	UpdatedAt time.Time `json:"updatedAt"`
	AdditionalProperties map[string]interface{}
}

type _LogicalNetworkInterconnect LogicalNetworkInterconnect

// NewLogicalNetworkInterconnect instantiates a new LogicalNetworkInterconnect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogicalNetworkInterconnect(revision string, id string, label string, name string, kind LogicalNetworkInterconnectKind, fabricInterconnectId int32, status LogicalNetworkInterconnectStatus, createdAt time.Time, updatedAt time.Time) *LogicalNetworkInterconnect {
	this := LogicalNetworkInterconnect{}
	this.Revision = revision
	this.Id = id
	this.Label = label
	this.Name = name
	this.Kind = kind
	this.FabricInterconnectId = fabricInterconnectId
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewLogicalNetworkInterconnectWithDefaults instantiates a new LogicalNetworkInterconnect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogicalNetworkInterconnectWithDefaults() *LogicalNetworkInterconnect {
	this := LogicalNetworkInterconnect{}
	return &this
}

// GetRevision returns the Revision field value
func (o *LogicalNetworkInterconnect) GetRevision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetRevisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *LogicalNetworkInterconnect) SetRevision(v string) {
	o.Revision = v
}

// GetId returns the Id field value
func (o *LogicalNetworkInterconnect) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LogicalNetworkInterconnect) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *LogicalNetworkInterconnect) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *LogicalNetworkInterconnect) SetLabel(v string) {
	o.Label = v
}

// GetName returns the Name field value
func (o *LogicalNetworkInterconnect) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LogicalNetworkInterconnect) SetName(v string) {
	o.Name = v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *LogicalNetworkInterconnect) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *LogicalNetworkInterconnect) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *LogicalNetworkInterconnect) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetKind returns the Kind field value
func (o *LogicalNetworkInterconnect) GetKind() LogicalNetworkInterconnectKind {
	if o == nil {
		var ret LogicalNetworkInterconnectKind
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetKindOk() (*LogicalNetworkInterconnectKind, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *LogicalNetworkInterconnect) SetKind(v LogicalNetworkInterconnectKind) {
	o.Kind = v
}

// GetFabricInterconnectId returns the FabricInterconnectId field value
func (o *LogicalNetworkInterconnect) GetFabricInterconnectId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FabricInterconnectId
}

// GetFabricInterconnectIdOk returns a tuple with the FabricInterconnectId field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetFabricInterconnectIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FabricInterconnectId, true
}

// SetFabricInterconnectId sets field value
func (o *LogicalNetworkInterconnect) SetFabricInterconnectId(v int32) {
	o.FabricInterconnectId = v
}

// GetTransportId returns the TransportId field value if set, zero value otherwise.
func (o *LogicalNetworkInterconnect) GetTransportId() int32 {
	if o == nil || IsNil(o.TransportId) {
		var ret int32
		return ret
	}
	return *o.TransportId
}

// GetTransportIdOk returns a tuple with the TransportId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetTransportIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TransportId) {
		return nil, false
	}
	return o.TransportId, true
}

// HasTransportId returns a boolean if a field has been set.
func (o *LogicalNetworkInterconnect) HasTransportId() bool {
	if o != nil && !IsNil(o.TransportId) {
		return true
	}

	return false
}

// SetTransportId gets a reference to the given int32 and assigns it to the TransportId field.
func (o *LogicalNetworkInterconnect) SetTransportId(v int32) {
	o.TransportId = &v
}

// GetStatus returns the Status field value
func (o *LogicalNetworkInterconnect) GetStatus() LogicalNetworkInterconnectStatus {
	if o == nil {
		var ret LogicalNetworkInterconnectStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetStatusOk() (*LogicalNetworkInterconnectStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LogicalNetworkInterconnect) SetStatus(v LogicalNetworkInterconnectStatus) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *LogicalNetworkInterconnect) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LogicalNetworkInterconnect) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *LogicalNetworkInterconnect) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkInterconnect) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *LogicalNetworkInterconnect) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o LogicalNetworkInterconnect) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogicalNetworkInterconnect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["revision"] = o.Revision
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["name"] = o.Name
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	toSerialize["kind"] = o.Kind
	toSerialize["fabricInterconnectId"] = o.FabricInterconnectId
	if !IsNil(o.TransportId) {
		toSerialize["transportId"] = o.TransportId
	}
	toSerialize["status"] = o.Status
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LogicalNetworkInterconnect) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"revision",
		"id",
		"label",
		"name",
		"kind",
		"fabricInterconnectId",
		"status",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogicalNetworkInterconnect := _LogicalNetworkInterconnect{}

	err = json.Unmarshal(data, &varLogicalNetworkInterconnect)

	if err != nil {
		return err
	}

	*o = LogicalNetworkInterconnect(varLogicalNetworkInterconnect)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "revision")
		delete(additionalProperties, "id")
		delete(additionalProperties, "label")
		delete(additionalProperties, "name")
		delete(additionalProperties, "annotations")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "fabricInterconnectId")
		delete(additionalProperties, "transportId")
		delete(additionalProperties, "status")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLogicalNetworkInterconnect struct {
	value *LogicalNetworkInterconnect
	isSet bool
}

func (v NullableLogicalNetworkInterconnect) Get() *LogicalNetworkInterconnect {
	return v.value
}

func (v *NullableLogicalNetworkInterconnect) Set(val *LogicalNetworkInterconnect) {
	v.value = val
	v.isSet = true
}

func (v NullableLogicalNetworkInterconnect) IsSet() bool {
	return v.isSet
}

func (v *NullableLogicalNetworkInterconnect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogicalNetworkInterconnect(val *LogicalNetworkInterconnect) *NullableLogicalNetworkInterconnect {
	return &NullableLogicalNetworkInterconnect{value: val, isSet: true}
}

func (v NullableLogicalNetworkInterconnect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogicalNetworkInterconnect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


