/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the PlatformUploadsDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlatformUploadsDto{}

// PlatformUploadsDto struct for PlatformUploadsDto
type PlatformUploadsDto struct {
	// Upload directory path on the platform service
	Bsi *string `json:"bsi,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PlatformUploadsDto PlatformUploadsDto

// NewPlatformUploadsDto instantiates a new PlatformUploadsDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlatformUploadsDto() *PlatformUploadsDto {
	this := PlatformUploadsDto{}
	return &this
}

// NewPlatformUploadsDtoWithDefaults instantiates a new PlatformUploadsDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlatformUploadsDtoWithDefaults() *PlatformUploadsDto {
	this := PlatformUploadsDto{}
	return &this
}

// GetBsi returns the Bsi field value if set, zero value otherwise.
func (o *PlatformUploadsDto) GetBsi() string {
	if o == nil || IsNil(o.Bsi) {
		var ret string
		return ret
	}
	return *o.Bsi
}

// GetBsiOk returns a tuple with the Bsi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlatformUploadsDto) GetBsiOk() (*string, bool) {
	if o == nil || IsNil(o.Bsi) {
		return nil, false
	}
	return o.Bsi, true
}

// HasBsi returns a boolean if a field has been set.
func (o *PlatformUploadsDto) HasBsi() bool {
	if o != nil && !IsNil(o.Bsi) {
		return true
	}

	return false
}

// SetBsi gets a reference to the given string and assigns it to the Bsi field.
func (o *PlatformUploadsDto) SetBsi(v string) {
	o.Bsi = &v
}

func (o PlatformUploadsDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlatformUploadsDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bsi) {
		toSerialize["bsi"] = o.Bsi
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PlatformUploadsDto) UnmarshalJSON(data []byte) (err error) {
	varPlatformUploadsDto := _PlatformUploadsDto{}

	err = json.Unmarshal(data, &varPlatformUploadsDto)

	if err != nil {
		return err
	}

	*o = PlatformUploadsDto(varPlatformUploadsDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "bsi")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePlatformUploadsDto struct {
	value *PlatformUploadsDto
	isSet bool
}

func (v NullablePlatformUploadsDto) Get() *PlatformUploadsDto {
	return v.value
}

func (v *NullablePlatformUploadsDto) Set(val *PlatformUploadsDto) {
	v.value = val
	v.isSet = true
}

func (v NullablePlatformUploadsDto) IsSet() bool {
	return v.isSet
}

func (v *NullablePlatformUploadsDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlatformUploadsDto(val *PlatformUploadsDto) *NullablePlatformUploadsDto {
	return &NullablePlatformUploadsDto{value: val, isSet: true}
}

func (v NullablePlatformUploadsDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlatformUploadsDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


