/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the GroupMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroupMapping{}

// GroupMapping struct for GroupMapping
type GroupMapping struct {
	// LDAP or SAML group name
	GroupName map[string]interface{} `json:"groupName"`
	// Application role assigned to members of this group
	RoleName map[string]interface{} `json:"roleName"`
	// Mapping priority — lower value wins when a user matches multiple groups
	Priority map[string]interface{} `json:"priority"`
	// Quota profile assigned to users matched by this group
	QuotaProfileId string `json:"quotaProfileId"`
	AdditionalProperties map[string]interface{}
}

type _GroupMapping GroupMapping

// NewGroupMapping instantiates a new GroupMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroupMapping(groupName map[string]interface{}, roleName map[string]interface{}, priority map[string]interface{}, quotaProfileId string) *GroupMapping {
	this := GroupMapping{}
	this.GroupName = groupName
	this.RoleName = roleName
	this.Priority = priority
	this.QuotaProfileId = quotaProfileId
	return &this
}

// NewGroupMappingWithDefaults instantiates a new GroupMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroupMappingWithDefaults() *GroupMapping {
	this := GroupMapping{}
	return &this
}

// GetGroupName returns the GroupName field value
func (o *GroupMapping) GetGroupName() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetGroupNameOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.GroupName, true
}

// SetGroupName sets field value
func (o *GroupMapping) SetGroupName(v map[string]interface{}) {
	o.GroupName = v
}

// GetRoleName returns the RoleName field value
func (o *GroupMapping) GetRoleName() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetRoleNameOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.RoleName, true
}

// SetRoleName sets field value
func (o *GroupMapping) SetRoleName(v map[string]interface{}) {
	o.RoleName = v
}

// GetPriority returns the Priority field value
func (o *GroupMapping) GetPriority() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetPriorityOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Priority, true
}

// SetPriority sets field value
func (o *GroupMapping) SetPriority(v map[string]interface{}) {
	o.Priority = v
}

// GetQuotaProfileId returns the QuotaProfileId field value
func (o *GroupMapping) GetQuotaProfileId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuotaProfileId
}

// GetQuotaProfileIdOk returns a tuple with the QuotaProfileId field value
// and a boolean to check if the value has been set.
func (o *GroupMapping) GetQuotaProfileIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotaProfileId, true
}

// SetQuotaProfileId sets field value
func (o *GroupMapping) SetQuotaProfileId(v string) {
	o.QuotaProfileId = v
}

func (o GroupMapping) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroupMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["groupName"] = o.GroupName
	toSerialize["roleName"] = o.RoleName
	toSerialize["priority"] = o.Priority
	toSerialize["quotaProfileId"] = o.QuotaProfileId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GroupMapping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"groupName",
		"roleName",
		"priority",
		"quotaProfileId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGroupMapping := _GroupMapping{}

	err = json.Unmarshal(data, &varGroupMapping)

	if err != nil {
		return err
	}

	*o = GroupMapping(varGroupMapping)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "groupName")
		delete(additionalProperties, "roleName")
		delete(additionalProperties, "priority")
		delete(additionalProperties, "quotaProfileId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGroupMapping struct {
	value *GroupMapping
	isSet bool
}

func (v NullableGroupMapping) Get() *GroupMapping {
	return v.value
}

func (v *NullableGroupMapping) Set(val *GroupMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableGroupMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableGroupMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroupMapping(val *GroupMapping) *NullableGroupMapping {
	return &NullableGroupMapping{value: val, isSet: true}
}

func (v NullableGroupMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroupMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


