/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
)

// checks if the EditRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditRole{}

// EditRole struct for EditRole
type EditRole struct {
	// Role label. Omit to keep the current value. Cannot be changed on built-in roles.
	Label *string `json:"label,omitempty"`
	// Role description. Omit to keep the current value. Cannot be changed on built-in roles.
	Description *string `json:"description,omitempty"`
	// List of permissions assigned to the role. Omit to keep the current value. Cannot be changed on built-in roles.
	Permissions []MetalsoftPermissions `json:"permissions,omitempty"`
	// Quota profile assigned to this role
	QuotaProfileId *string `json:"quotaProfileId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EditRole EditRole

// NewEditRole instantiates a new EditRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditRole() *EditRole {
	this := EditRole{}
	return &this
}

// NewEditRoleWithDefaults instantiates a new EditRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditRoleWithDefaults() *EditRole {
	this := EditRole{}
	return &this
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *EditRole) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditRole) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *EditRole) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *EditRole) SetLabel(v string) {
	o.Label = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *EditRole) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditRole) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *EditRole) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *EditRole) SetDescription(v string) {
	o.Description = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *EditRole) GetPermissions() []MetalsoftPermissions {
	if o == nil || IsNil(o.Permissions) {
		var ret []MetalsoftPermissions
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditRole) GetPermissionsOk() ([]MetalsoftPermissions, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *EditRole) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []MetalsoftPermissions and assigns it to the Permissions field.
func (o *EditRole) SetPermissions(v []MetalsoftPermissions) {
	o.Permissions = v
}

// GetQuotaProfileId returns the QuotaProfileId field value if set, zero value otherwise.
func (o *EditRole) GetQuotaProfileId() string {
	if o == nil || IsNil(o.QuotaProfileId) {
		var ret string
		return ret
	}
	return *o.QuotaProfileId
}

// GetQuotaProfileIdOk returns a tuple with the QuotaProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditRole) GetQuotaProfileIdOk() (*string, bool) {
	if o == nil || IsNil(o.QuotaProfileId) {
		return nil, false
	}
	return o.QuotaProfileId, true
}

// HasQuotaProfileId returns a boolean if a field has been set.
func (o *EditRole) HasQuotaProfileId() bool {
	if o != nil && !IsNil(o.QuotaProfileId) {
		return true
	}

	return false
}

// SetQuotaProfileId gets a reference to the given string and assigns it to the QuotaProfileId field.
func (o *EditRole) SetQuotaProfileId(v string) {
	o.QuotaProfileId = &v
}

func (o EditRole) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.QuotaProfileId) {
		toSerialize["quotaProfileId"] = o.QuotaProfileId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *EditRole) UnmarshalJSON(data []byte) (err error) {
	varEditRole := _EditRole{}

	err = json.Unmarshal(data, &varEditRole)

	if err != nil {
		return err
	}

	*o = EditRole(varEditRole)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "label")
		delete(additionalProperties, "description")
		delete(additionalProperties, "permissions")
		delete(additionalProperties, "quotaProfileId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEditRole struct {
	value *EditRole
	isSet bool
}

func (v NullableEditRole) Get() *EditRole {
	return v.value
}

func (v *NullableEditRole) Set(val *EditRole) {
	v.value = val
	v.isSet = true
}

func (v NullableEditRole) IsSet() bool {
	return v.isSet
}

func (v *NullableEditRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditRole(val *EditRole) *NullableEditRole {
	return &NullableEditRole{value: val, isSet: true}
}

func (v NullableEditRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


