/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the VrfAllocation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VrfAllocation{}

// VrfAllocation struct for VrfAllocation
type VrfAllocation struct {
	Id int32 `json:"id"`
	Scope ResourceScope `json:"scope"`
	Status ResourceAllocationStatus `json:"status"`
	Name string `json:"name"`
	AdditionalProperties map[string]interface{}
}

type _VrfAllocation VrfAllocation

// NewVrfAllocation instantiates a new VrfAllocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVrfAllocation(id int32, scope ResourceScope, status ResourceAllocationStatus, name string) *VrfAllocation {
	this := VrfAllocation{}
	this.Id = id
	this.Scope = scope
	this.Status = status
	this.Name = name
	return &this
}

// NewVrfAllocationWithDefaults instantiates a new VrfAllocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVrfAllocationWithDefaults() *VrfAllocation {
	this := VrfAllocation{}
	return &this
}

// GetId returns the Id field value
func (o *VrfAllocation) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *VrfAllocation) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *VrfAllocation) SetId(v int32) {
	o.Id = v
}

// GetScope returns the Scope field value
func (o *VrfAllocation) GetScope() ResourceScope {
	if o == nil {
		var ret ResourceScope
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *VrfAllocation) GetScopeOk() (*ResourceScope, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *VrfAllocation) SetScope(v ResourceScope) {
	o.Scope = v
}

// GetStatus returns the Status field value
func (o *VrfAllocation) GetStatus() ResourceAllocationStatus {
	if o == nil {
		var ret ResourceAllocationStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *VrfAllocation) GetStatusOk() (*ResourceAllocationStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *VrfAllocation) SetStatus(v ResourceAllocationStatus) {
	o.Status = v
}

// GetName returns the Name field value
func (o *VrfAllocation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *VrfAllocation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *VrfAllocation) SetName(v string) {
	o.Name = v
}

func (o VrfAllocation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VrfAllocation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["scope"] = o.Scope
	toSerialize["status"] = o.Status
	toSerialize["name"] = o.Name

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VrfAllocation) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"scope",
		"status",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVrfAllocation := _VrfAllocation{}

	err = json.Unmarshal(data, &varVrfAllocation)

	if err != nil {
		return err
	}

	*o = VrfAllocation(varVrfAllocation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "status")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVrfAllocation struct {
	value *VrfAllocation
	isSet bool
}

func (v NullableVrfAllocation) Get() *VrfAllocation {
	return v.value
}

func (v *NullableVrfAllocation) Set(val *VrfAllocation) {
	v.value = val
	v.isSet = true
}

func (v NullableVrfAllocation) IsSet() bool {
	return v.isSet
}

func (v *NullableVrfAllocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVrfAllocation(val *VrfAllocation) *NullableVrfAllocation {
	return &NullableVrfAllocation{value: val, isSet: true}
}

func (v NullableVrfAllocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVrfAllocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


