/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the LogicalNetworkPkeyProperties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LogicalNetworkPkeyProperties{}

// LogicalNetworkPkeyProperties struct for LogicalNetworkPkeyProperties
type LogicalNetworkPkeyProperties struct {
	Pkeys []PkeyAllocation `json:"pkeys"`
	PkeyAllocationStrategies []PkeyAllocationStrategy1 `json:"pkeyAllocationStrategies"`
	AdditionalProperties map[string]interface{}
}

type _LogicalNetworkPkeyProperties LogicalNetworkPkeyProperties

// NewLogicalNetworkPkeyProperties instantiates a new LogicalNetworkPkeyProperties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLogicalNetworkPkeyProperties(pkeys []PkeyAllocation, pkeyAllocationStrategies []PkeyAllocationStrategy1) *LogicalNetworkPkeyProperties {
	this := LogicalNetworkPkeyProperties{}
	this.Pkeys = pkeys
	this.PkeyAllocationStrategies = pkeyAllocationStrategies
	return &this
}

// NewLogicalNetworkPkeyPropertiesWithDefaults instantiates a new LogicalNetworkPkeyProperties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLogicalNetworkPkeyPropertiesWithDefaults() *LogicalNetworkPkeyProperties {
	this := LogicalNetworkPkeyProperties{}
	return &this
}

// GetPkeys returns the Pkeys field value
func (o *LogicalNetworkPkeyProperties) GetPkeys() []PkeyAllocation {
	if o == nil {
		var ret []PkeyAllocation
		return ret
	}

	return o.Pkeys
}

// GetPkeysOk returns a tuple with the Pkeys field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkPkeyProperties) GetPkeysOk() ([]PkeyAllocation, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pkeys, true
}

// SetPkeys sets field value
func (o *LogicalNetworkPkeyProperties) SetPkeys(v []PkeyAllocation) {
	o.Pkeys = v
}

// GetPkeyAllocationStrategies returns the PkeyAllocationStrategies field value
func (o *LogicalNetworkPkeyProperties) GetPkeyAllocationStrategies() []PkeyAllocationStrategy1 {
	if o == nil {
		var ret []PkeyAllocationStrategy1
		return ret
	}

	return o.PkeyAllocationStrategies
}

// GetPkeyAllocationStrategiesOk returns a tuple with the PkeyAllocationStrategies field value
// and a boolean to check if the value has been set.
func (o *LogicalNetworkPkeyProperties) GetPkeyAllocationStrategiesOk() ([]PkeyAllocationStrategy1, bool) {
	if o == nil {
		return nil, false
	}
	return o.PkeyAllocationStrategies, true
}

// SetPkeyAllocationStrategies sets field value
func (o *LogicalNetworkPkeyProperties) SetPkeyAllocationStrategies(v []PkeyAllocationStrategy1) {
	o.PkeyAllocationStrategies = v
}

func (o LogicalNetworkPkeyProperties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LogicalNetworkPkeyProperties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pkeys"] = o.Pkeys
	toSerialize["pkeyAllocationStrategies"] = o.PkeyAllocationStrategies

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *LogicalNetworkPkeyProperties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pkeys",
		"pkeyAllocationStrategies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLogicalNetworkPkeyProperties := _LogicalNetworkPkeyProperties{}

	err = json.Unmarshal(data, &varLogicalNetworkPkeyProperties)

	if err != nil {
		return err
	}

	*o = LogicalNetworkPkeyProperties(varLogicalNetworkPkeyProperties)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "pkeys")
		delete(additionalProperties, "pkeyAllocationStrategies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableLogicalNetworkPkeyProperties struct {
	value *LogicalNetworkPkeyProperties
	isSet bool
}

func (v NullableLogicalNetworkPkeyProperties) Get() *LogicalNetworkPkeyProperties {
	return v.value
}

func (v *NullableLogicalNetworkPkeyProperties) Set(val *LogicalNetworkPkeyProperties) {
	v.value = val
	v.isSet = true
}

func (v NullableLogicalNetworkPkeyProperties) IsSet() bool {
	return v.isSet
}

func (v *NullableLogicalNetworkPkeyProperties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLogicalNetworkPkeyProperties(val *LogicalNetworkPkeyProperties) *NullableLogicalNetworkPkeyProperties {
	return &NullableLogicalNetworkPkeyProperties{value: val, isSet: true}
}

func (v NullableLogicalNetworkPkeyProperties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLogicalNetworkPkeyProperties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


