/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// SwitchDriver The device driver this template applies to. Used for filtering and validation purposes.
type SwitchDriver string

// List of SwitchDriver
const (
	SWITCHDRIVER_CISCO_ACI51 SwitchDriver = "cisco_aci51"
	SWITCHDRIVER_CISCO_NDFC SwitchDriver = "cisco_ndfc"
	SWITCHDRIVER_NVIDIA_UFM SwitchDriver = "nvidia_ufm"
	SWITCHDRIVER_NEXUS9000 SwitchDriver = "nexus9000"
	SWITCHDRIVER_CUMULUS42 SwitchDriver = "cumulus42"
	SWITCHDRIVER_ARISTA_EOS SwitchDriver = "arista_eos"
	SWITCHDRIVER_DELL_S4048 SwitchDriver = "dell_s4048"
	SWITCHDRIVER_HP5800 SwitchDriver = "hp5800"
	SWITCHDRIVER_HP5900 SwitchDriver = "hp5900"
	SWITCHDRIVER_HP5950 SwitchDriver = "hp5950"
	SWITCHDRIVER_DUMMY SwitchDriver = "dummy"
	SWITCHDRIVER_JUNOS SwitchDriver = "junos"
	SWITCHDRIVER_OS_10 SwitchDriver = "os_10"
	SWITCHDRIVER_SONIC_ENTERPRISE SwitchDriver = "sonic_enterprise"
	SWITCHDRIVER_VMWARE_VDS SwitchDriver = "vmware_vds"
	SWITCHDRIVER_CUMULUS_LINUX SwitchDriver = "cumulus_linux"
	SWITCHDRIVER_BROCADE SwitchDriver = "brocade"
	SWITCHDRIVER_NVIDIA_DPU SwitchDriver = "nvidia_dpu"
	SWITCHDRIVER_DELL_S4000 SwitchDriver = "dell_s4000"
	SWITCHDRIVER_DELL_S6010 SwitchDriver = "dell_s6010"
	SWITCHDRIVER_JUNOS18 SwitchDriver = "junos18"
)

// All allowed values of SwitchDriver enum
var AllowedSwitchDriverEnumValues = []SwitchDriver{
	"cisco_aci51",
	"cisco_ndfc",
	"nvidia_ufm",
	"nexus9000",
	"cumulus42",
	"arista_eos",
	"dell_s4048",
	"hp5800",
	"hp5900",
	"hp5950",
	"dummy",
	"junos",
	"os_10",
	"sonic_enterprise",
	"vmware_vds",
	"cumulus_linux",
	"brocade",
	"nvidia_dpu",
	"dell_s4000",
	"dell_s6010",
	"junos18",
}

func (v *SwitchDriver) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := SwitchDriver(value)
	for _, existing := range AllowedSwitchDriverEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid SwitchDriver", value)
}

// NewSwitchDriverFromValue returns a pointer to a valid SwitchDriver
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSwitchDriverFromValue(v string) (*SwitchDriver, error) {
	ev := SwitchDriver(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for SwitchDriver: valid values are %v", v, AllowedSwitchDriverEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v SwitchDriver) IsValid() bool {
	for _, existing := range AllowedSwitchDriverEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to SwitchDriver value
func (v SwitchDriver) Ptr() *SwitchDriver {
	return &v
}

type NullableSwitchDriver struct {
	value *SwitchDriver
	isSet bool
}

func (v NullableSwitchDriver) Get() *SwitchDriver {
	return v.value
}

func (v *NullableSwitchDriver) Set(val *SwitchDriver) {
	v.value = val
	v.isSet = true
}

func (v NullableSwitchDriver) IsSet() bool {
	return v.isSet
}

func (v *NullableSwitchDriver) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSwitchDriver(val *SwitchDriver) *NullableSwitchDriver {
	return &NullableSwitchDriver{value: val, isSet: true}
}

func (v NullableSwitchDriver) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSwitchDriver) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

