/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateExternalConnectionInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateExternalConnectionInterface{}

// UpdateExternalConnectionInterface struct for UpdateExternalConnectionInterface
type UpdateExternalConnectionInterface struct {
	// Network device interface id
	NetworkDeviceInterfaceId float32 `json:"networkDeviceInterfaceId"`
	AdditionalProperties map[string]interface{}
}

type _UpdateExternalConnectionInterface UpdateExternalConnectionInterface

// NewUpdateExternalConnectionInterface instantiates a new UpdateExternalConnectionInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateExternalConnectionInterface(networkDeviceInterfaceId float32) *UpdateExternalConnectionInterface {
	this := UpdateExternalConnectionInterface{}
	this.NetworkDeviceInterfaceId = networkDeviceInterfaceId
	return &this
}

// NewUpdateExternalConnectionInterfaceWithDefaults instantiates a new UpdateExternalConnectionInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateExternalConnectionInterfaceWithDefaults() *UpdateExternalConnectionInterface {
	this := UpdateExternalConnectionInterface{}
	return &this
}

// GetNetworkDeviceInterfaceId returns the NetworkDeviceInterfaceId field value
func (o *UpdateExternalConnectionInterface) GetNetworkDeviceInterfaceId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.NetworkDeviceInterfaceId
}

// GetNetworkDeviceInterfaceIdOk returns a tuple with the NetworkDeviceInterfaceId field value
// and a boolean to check if the value has been set.
func (o *UpdateExternalConnectionInterface) GetNetworkDeviceInterfaceIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkDeviceInterfaceId, true
}

// SetNetworkDeviceInterfaceId sets field value
func (o *UpdateExternalConnectionInterface) SetNetworkDeviceInterfaceId(v float32) {
	o.NetworkDeviceInterfaceId = v
}

func (o UpdateExternalConnectionInterface) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateExternalConnectionInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["networkDeviceInterfaceId"] = o.NetworkDeviceInterfaceId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateExternalConnectionInterface) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"networkDeviceInterfaceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateExternalConnectionInterface := _UpdateExternalConnectionInterface{}

	err = json.Unmarshal(data, &varUpdateExternalConnectionInterface)

	if err != nil {
		return err
	}

	*o = UpdateExternalConnectionInterface(varUpdateExternalConnectionInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "networkDeviceInterfaceId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateExternalConnectionInterface struct {
	value *UpdateExternalConnectionInterface
	isSet bool
}

func (v NullableUpdateExternalConnectionInterface) Get() *UpdateExternalConnectionInterface {
	return v.value
}

func (v *NullableUpdateExternalConnectionInterface) Set(val *UpdateExternalConnectionInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateExternalConnectionInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateExternalConnectionInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateExternalConnectionInterface(val *UpdateExternalConnectionInterface) *NullableUpdateExternalConnectionInterface {
	return &NullableUpdateExternalConnectionInterface{value: val, isSet: true}
}

func (v NullableUpdateExternalConnectionInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateExternalConnectionInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


