/*
MetalSoft REST API

MetalSoft REST API documentation

API version: 2.0
Contact: support@metalsoft.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sdk

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateLogicalNetworkIpv4Properties type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateLogicalNetworkIpv4Properties{}

// CreateLogicalNetworkIpv4Properties struct for CreateLogicalNetworkIpv4Properties
type CreateLogicalNetworkIpv4Properties struct {
	SubnetAllocationStrategies []CreateIpv4SubnetAllocationStrategy1 `json:"subnetAllocationStrategies"`
	AdditionalProperties map[string]interface{}
}

type _CreateLogicalNetworkIpv4Properties CreateLogicalNetworkIpv4Properties

// NewCreateLogicalNetworkIpv4Properties instantiates a new CreateLogicalNetworkIpv4Properties object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLogicalNetworkIpv4Properties(subnetAllocationStrategies []CreateIpv4SubnetAllocationStrategy1) *CreateLogicalNetworkIpv4Properties {
	this := CreateLogicalNetworkIpv4Properties{}
	this.SubnetAllocationStrategies = subnetAllocationStrategies
	return &this
}

// NewCreateLogicalNetworkIpv4PropertiesWithDefaults instantiates a new CreateLogicalNetworkIpv4Properties object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLogicalNetworkIpv4PropertiesWithDefaults() *CreateLogicalNetworkIpv4Properties {
	this := CreateLogicalNetworkIpv4Properties{}
	return &this
}

// GetSubnetAllocationStrategies returns the SubnetAllocationStrategies field value
func (o *CreateLogicalNetworkIpv4Properties) GetSubnetAllocationStrategies() []CreateIpv4SubnetAllocationStrategy1 {
	if o == nil {
		var ret []CreateIpv4SubnetAllocationStrategy1
		return ret
	}

	return o.SubnetAllocationStrategies
}

// GetSubnetAllocationStrategiesOk returns a tuple with the SubnetAllocationStrategies field value
// and a boolean to check if the value has been set.
func (o *CreateLogicalNetworkIpv4Properties) GetSubnetAllocationStrategiesOk() ([]CreateIpv4SubnetAllocationStrategy1, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubnetAllocationStrategies, true
}

// SetSubnetAllocationStrategies sets field value
func (o *CreateLogicalNetworkIpv4Properties) SetSubnetAllocationStrategies(v []CreateIpv4SubnetAllocationStrategy1) {
	o.SubnetAllocationStrategies = v
}

func (o CreateLogicalNetworkIpv4Properties) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateLogicalNetworkIpv4Properties) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["subnetAllocationStrategies"] = o.SubnetAllocationStrategies

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateLogicalNetworkIpv4Properties) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"subnetAllocationStrategies",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateLogicalNetworkIpv4Properties := _CreateLogicalNetworkIpv4Properties{}

	err = json.Unmarshal(data, &varCreateLogicalNetworkIpv4Properties)

	if err != nil {
		return err
	}

	*o = CreateLogicalNetworkIpv4Properties(varCreateLogicalNetworkIpv4Properties)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "subnetAllocationStrategies")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateLogicalNetworkIpv4Properties struct {
	value *CreateLogicalNetworkIpv4Properties
	isSet bool
}

func (v NullableCreateLogicalNetworkIpv4Properties) Get() *CreateLogicalNetworkIpv4Properties {
	return v.value
}

func (v *NullableCreateLogicalNetworkIpv4Properties) Set(val *CreateLogicalNetworkIpv4Properties) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLogicalNetworkIpv4Properties) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLogicalNetworkIpv4Properties) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLogicalNetworkIpv4Properties(val *CreateLogicalNetworkIpv4Properties) *NullableCreateLogicalNetworkIpv4Properties {
	return &NullableCreateLogicalNetworkIpv4Properties{value: val, isSet: true}
}

func (v NullableCreateLogicalNetworkIpv4Properties) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateLogicalNetworkIpv4Properties) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


